// apps/web/src/lib/snippets/capture.svelte
<script lang="ts">
  import { localUser } from '../manabi/client';
  import Shelf from './shelf.svelte';
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { resolve } from '$app/paths';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Dialog from '$lib/components/ui/dialog';
  import { scope, snippetItems, flushSnippets, appendToSnippet } from './service';
  import { saveDraft, deleteDraft, recordKey } from './database';
  import {
    createSnippet,
    passages,
    snippetKey,
    type SnippetDocument,
    type TextNode
  } from './document';
  let open = false,
    busy = false,
    error = '',
    query = '';
  let content: TextNode | undefined,
    document: SnippetDocument | undefined,
    session = '',
    captured: ReturnType<typeof scope> | undefined;
  $: choices = $snippetItems.filter((item) => !item.trashedAt && !item.transfer && !item.conflicts);
  async function create() {
    if (!captured || !content || !document || busy) return;
    busy = true;
    try {
      captured.guard();
      open = false;
      await goto(resolve(`/snippets?draft=${encodeURIComponent(session)}`));
    } catch (reason) {
      error = reason instanceof Error ? reason.message : 'The capture remains in recovered drafts.';
    } finally {
      busy = false;
    }
  }
  async function append(id: string) {
    if (!captured || !content || busy) return;
    busy = true;
    error = '';
    try {
      const selected = captured,
        text = content;
      await appendToSnippet(id, text, session, selected);
      await deleteDraft(recordKey(selected.owner, session), selected.guard);
      open = false;
      void flushSnippets(selected).catch(() => undefined);
    } catch (reason) {
      error = reason instanceof Error ? reason.message : 'The capture is preserved as a draft.';
    } finally {
      busy = false;
    }
  }
  onMount(() => {
    let alive = true;
    const receive = async (event: Event) => {
      if (open || busy) return;
      busy = true;
      const value = (
        event as CustomEvent<{ html: string; title: string; item: string; owner: string | null }>
      ).detail;
      try {
        const selected = scope();
        if (selected.owner !== (value.owner ? `account:${value.owner}` : 'local'))
          throw new Error('The account changed before capture.');
        const { importContent } = await import('./editor');
        selected.guard();
        const text = importContent(value.html, 'html');
        const created = createSnippet(text);
        created.source = {
          title: value.title.slice(0, 1000),
          item: value.item.slice(0, 1000),
          quote: passages(text)
            .map((p) => p.text)
            .join('\n')
            .slice(0, 4000)
        };
        const key = crypto.randomUUID();
        await saveDraft(
          {
            key: recordKey(selected.owner, key),
            owner: selected.owner,
            id: created.id,
            session: key,
            base: null,
            document: created,
            updatedAt: Date.now(),
            mode: 'new'
          },
          selected.guard
        );
        selected.guard();
        if (!alive) return;
        captured = selected;
        content = text;
        document = created;
        session = key;
        query = '';
        error = '';
        open = true;
      } catch (reason) {
        error = reason instanceof Error ? reason.message : 'The selection could not be captured.';
      } finally {
        busy = false;
      }
    };
    const stopAccount = localUser.subscribe(() => {
      try {
        captured?.guard();
      } catch {
        open = false;
        content = undefined;
        document = undefined;
        captured = undefined;
        query = '';
        error = '';
      }
    });
    window.addEventListener('manabi-capture-snippet', receive);
    return () => {
      alive = false;
      stopAccount();
      window.removeEventListener('manabi-capture-snippet', receive);
    };
  });
</script>

{#if open}
  <Dialog.Root bind:open>
    <Dialog.Content closeDisabled={busy}>
      <Dialog.Header
        ><Dialog.Title>Add to snippet</Dialog.Title><Dialog.Description
          >The captured text is already kept as a local draft. Choose a destination.</Dialog.Description
        ></Dialog.Header
      >
      <Button disabled={busy} onclick={create}>Create new snippet</Button>
      <Input
        class="min-h-11"
        aria-label="Search destination snippets"
        placeholder="Search existing snippets"
        bind:value={query}
        maxlength={512}
      />
      <div class="choices">
        <Shelf
          {query}
          members={choices.map((item) => snippetKey(item.id))}
          onchoose={(item) => void append(item.id)}
        />
      </div>
      {#if error}<p role="alert">{error}</p>{/if}<Button
        variant="secondary"
        disabled={busy}
        onclick={() => (open = false)}>Keep for later</Button
      >
    </Dialog.Content>
  </Dialog.Root>
{:else if error}<div role="alert" class="capture-error">
    <span>{error}</span><Button variant="ghost" size="sm" onclick={() => (error = '')}
      >Dismiss</Button
    >
  </div>{/if}

<style>
  .choices {
    display: grid;
    max-height: 18rem;
    overflow-y: auto;
    gap: 0.3rem;
  }
  .capture-error {
    position: fixed;
    inset-inline: 1rem;
    bottom: max(1rem, env(safe-area-inset-bottom));
    z-index: 60;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    max-width: 40rem;
    margin-inline: auto;
    padding: 1rem;
    border: 1px solid var(--border);
    border-radius: 1rem;
    background: var(--card);
    box-shadow: 0 8px 30px #0002;
  }
</style>

// apps/web/src/snippets-react/capture.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, Button, Input, AppNav, DynamicComponent, Dialog, Menu, ReaderScope, useLatest, useReaderBindings, type ReaderViewProps } from './primitives';
import { createCapture, type CaptureProps } from './capture-controller';
import { localUser } from '../lib/manabi/client';
import { goto } from '$app/navigation';
import { resolve } from '$app/paths';
import { scope, snippetItems, flushSnippets, appendToSnippet } from '../lib/snippets/service';
import { saveDraft, deleteDraft, recordKey } from '../lib/snippets/database';
import {
    createSnippet,
    passages,
    snippetKey,
    type SnippetDocument,
    type TextNode
  } from '../lib/snippets/document';
import { Shelf } from './shelf';


export function SnippetCapture(props: CaptureProps & ReaderViewProps) {
const latest = useLatest(props);
const c = useReaderController(() => createCapture(props as CaptureProps, (name, detail) => latest.current.events?.[name]?.({ detail })), props);
useReaderBindings(c, props);
if (!c) return null;
return <ReaderScope name="react-snippets-capture">
{(c.open) ? <><Dialog.Root  open={c.open}
bindings={{"open": (value) => { c.open = value; }}}>
<Dialog.Content  closeDisabled={c.busy}>
<Dialog.Header  ><Dialog.Title  >{"Add to snippet"}</Dialog.Title><Dialog.Description  >{"The captured text is already kept as a local draft. Choose a destination."}</Dialog.Description></Dialog.Header>
<Button  disabled={c.busy}
onClick={c.create}>{"Create new snippet"}</Button>
<Input  aria-label={"Search destination snippets"}
placeholder={"Search existing snippets"}
value={c.query}
maxLength={512}
className={["min-h-11"].filter(Boolean).join(' ')}
bindings={{"value": (value) => { c.query = value; }}}></Input>
<Dom scopeClass="snippet-scope-capture" as="div" className={["choices"].filter(Boolean).join(' ')}>
<Shelf  query={c.query}
members={c.choices.map((item) => snippetKey(item.id))}
onchoose={(item) => void c.append(item.id)}></Shelf>
</Dom>
{(c.error) ? <><Dom scopeClass="snippet-scope-capture" as="p" role={"alert"}>{c.error}</Dom></> : null}<Button  variant={"secondary"}
disabled={c.busy}
onClick={() => (c.open = false)}>{"Keep for later"}</Button>
</Dialog.Content>
</Dialog.Root></> : <> {(c.error) ? <><Dom scopeClass="snippet-scope-capture" as="div" role={"alert"}
className={["capture-error"].filter(Boolean).join(' ')}>
<Dom scopeClass="snippet-scope-capture" as="span" >{c.error}</Dom><Button  variant={"ghost"}
size={"sm"}
onClick={() => (c.error = '')}>{"Dismiss"}</Button>
</Dom></> : null}</>}
</ReaderScope>;
}
