// apps/web/src/lib/snippets/destination-picker.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { resolve } from '$app/paths';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { FolderOpenIcon as FolderOpen } from 'phosphor-svelte';
  import { sourceDescriptors, type SourceDescriptor } from '../library/catalog';
  import { providerLabels, requestDocumentWriteAccess } from '../manabi/client';
  import { integrationDB } from '../manabi/persistence';
  import { reconnectLocalLibrary } from '../manabi/sources';
  import type { Destination, Guard } from './database';
  import { capability, folders, makeFolder, type StorageCapability } from './storage';
  export let initial: Destination | undefined = undefined;
  export let guard: Guard;
  export let choose: (destination: Destination | undefined, remember: boolean) => void;
  export let allowDevice = true;
  export let allowUnsetDefault = false;
  let sources: SourceDescriptor[] = [];
  let selected: SourceDescriptor | undefined;
  let trailNav: HTMLElement | null = null;
  let trail: { id: string; name: string }[] = [];
  let entries: { id: string; name: string }[] = [];
  let capabilities: StorageCapability | undefined;
  let remember = false,
    busy = false,
    error = '',
    newName = '',
    generation = 0;
  const identity = (source: SourceDescriptor) =>
    JSON.stringify([source.owner, source.id, source.root]);
  const providerName = (provider: string) =>
    providerLabels[provider] ??
    (provider === 'local' ? 'Local folder' : provider === 'webdav' ? 'WebDAV' : provider);
  $: parent = trail.at(-1)?.id ?? selected?.root ?? '';
  async function browse(
    source: SourceDescriptor,
    path = source.root,
    name = source.name,
    reset = false
  ) {
    const run = ++generation;
    busy = true;
    error = '';
    try {
      guard();
      const cap = await capability(source, guard);
      guard();
      const children = await folders(source, path, guard);
      guard();
      if (run !== generation) return;
      selected = source;
      capabilities = cap;
      entries = children;
      trail = reset
        ? [
            { id: source.root, name: source.name },
            ...(path !== source.root ? [{ id: path, name }] : [])
          ]
        : [...trail, { id: path, name }];
    } catch (reason) {
      if (run === generation)
        error = reason instanceof Error ? reason.message : 'Cannot browse this source.';
    } finally {
      if (run === generation) busy = false;
    }
  }
  async function navigate(source: SourceDescriptor, path: string, name: string) {
    await browse(source, path, name);
    await tick();
    trailNav?.querySelector<HTMLButtonElement>('button:last-of-type')?.focus({ preventScroll: true });
  }
  async function grant() {
    if (!selected || busy) return;
    const source = selected;
    busy = true;
    error = '';
    try {
      guard();
      if (source.owner) {
        if (!['google', 'dropbox', 'onedrive'].includes(source.provider))
          throw new Error('This provider does not support document writes.');
        await requestDocumentWriteAccess(source.provider, source.id);
        guard();
      } else if (source.provider === 'local') {
        const entry = await (await integrationDB()).get('localLibraries', source.id);
        guard();
        if (!entry) throw new Error('Reconnect this folder.');
        await reconnectLocalLibrary(entry, true);
        guard();
        await browse(source, parent, trail.at(-1)?.name, true);
      }
    } catch (reason) {
      error = reason instanceof Error ? reason.message : 'Permission could not be granted.';
    } finally {
      busy = false;
    }
  }
  async function mkdir() {
    if (!selected || !newName.trim() || busy) return;
    busy = true;
    error = '';
    try {
      const id = await makeFolder({ source: selected, parent }, newName.trim(), guard);
      await browse(selected, id, newName.trim());
      newName = '';
    } catch (reason) {
      error = reason instanceof Error ? reason.message : 'The folder could not be created.';
    } finally {
      busy = false;
    }
  }
  onMount(() => {
    let live = true;
    void (async () => {
      try {
        const found = await sourceDescriptors();
        guard();
        if (!live) return;
        sources = found;
        const original =
          initial && found.find((source) => identity(source) === identity(initial!.source));
        if (original)
          await browse(original, initial!.parent, initial!.parent || original.name, true);
        else if (sources.length === 1)
          await browse(sources[0], sources[0].root, sources[0].name, true);
      } catch (reason) {
        if (live) error = reason instanceof Error ? reason.message : 'Cannot load destinations.';
      }
    })();
    return () => {
      live = false;
      generation++;
    };
  });
</script>

<div class="destination-picker">
  <p>
    Save the document in one connected location. Collections and reading history stay attached when
    it moves.
  </p>
  <label
    >Storage source
    <select
      class="control-select"
      aria-label="Storage source"
      value={selected ? identity(selected) : ''}
      onchange={(event) => {
        const source = sources.find((item) => identity(item) === event.currentTarget.value);
        if (source) void browse(source, source.root, source.name, true);
      }}
    >
      <option value="" disabled>Choose a source</option>
      {#each sources as source (identity(source))}<option value={identity(source)}
          >{providerName(source.provider)} · {source.name}</option
        >{/each}
    </select>
  </label>
  {#if selected}
    <nav aria-label="Destination folder" class="breadcrumbs" bind:this={trailNav}>
      {#each trail as part, index (part.id)}
        <Button
          variant="link"
          size="sm"
          class="min-h-11 px-1"
          aria-current={index === trail.length - 1 ? 'page' : undefined}
          disabled={busy}
          onclick={() => {
            trail = trail.slice(0, index);
            void navigate(selected!, part.id, part.name);
          }}>{part.name || 'Root'}</Button
        >
        {#if index < trail.length - 1}<span aria-hidden="true">›</span>{/if}
      {/each}
    </nav>
    <div class="folder-list" aria-busy={busy}>
      {#each entries as folder (folder.id)}
        <Button
          variant="ghost"
          shape="rounded"
          class="min-h-11 w-full justify-start px-3 text-left"
          disabled={busy}
          onclick={() => navigate(selected!, folder.id, folder.name)}
        >
          <FolderOpen class="size-4 shrink-0" aria-hidden="true" />
          <span class="min-w-0 break-words">{folder.name}</span>
        </Button>
      {:else}
        <p>{busy ? 'Loading folders…' : 'No subfolders. You can save here.'}</p>
      {/each}
    </div>
    {#if selected.provider === 'local'}<p>
        Close other applications editing these files before saving. This browser cannot lock out
        external file editors.
      </p>{/if}
    {#if capabilities?.write}
      <form
        onsubmit={(event) => {
          event.preventDefault();
          void mkdir();
        }}
      >
        <Input
          aria-label="New folder name"
          class="min-h-11"
          placeholder="New folder name"
          bind:value={newName}
          maxlength="100"
        />
        <Button type="submit" variant="secondary" disabled={busy || !newName.trim()}
          >Create folder</Button
        >
      </form>
      <label class="remember"
        ><input class="size-5 accent-primary" type="checkbox" bind:checked={remember} /> Use this
        location for new snippets</label
      >
      <Button disabled={busy} onclick={() => choose({ source: selected!, parent }, remember)}
        >Use this folder</Button
      >
    {:else if capabilities}
      <p>
        {capabilities.reason ||
          'This source is read-only. Authorize document editing to save here.'}
      </p>
      {#if selected.provider !== 'webdav' && !capabilities.reason}<Button
          disabled={busy}
          onclick={grant}>Allow document editing</Button
        >{/if}
      {#if selected.provider === 'google'}<p>
          Google will request access to files in your Drive so Manabi can edit documents inside your
          selected library folders.
        </p>{/if}
    {/if}
  {/if}
  {#if allowDevice}<Button variant="ghost" onclick={() => choose(undefined, false)}
      >Keep on this device only</Button
    >{/if}
  {#if allowUnsetDefault}<Button variant="ghost" onclick={() => choose(undefined, false)}
      >Clear default location</Button
    >{/if}
  <Button href={resolve('/connections')} variant="link" size="sm" class="min-h-11 justify-start px-0"
    >Manage connected libraries</Button
  >
  {#if error}<p role="alert">{error}</p>{/if}
</div>

<style>
  .destination-picker {
    display: grid;
    gap: 1rem;
  }
  label {
    display: grid;
    gap: 0.4rem;
  }
  .control-select {
    min-height: 44px;
    width: 100%;
    border: 1px solid var(--input);
    border-radius: 10px;
    background: var(--background);
    color: var(--foreground);
    padding: 0.6rem 0.75rem;
  }
  .control-select:focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 2px;
  }
  .breadcrumbs {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.15rem;
    min-width: 0;
  }
  .folder-list {
    max-height: 14rem;
    overflow-y: auto;
    display: grid;
    gap: 0.3rem;
  }
  .folder-list p {
    padding: 0.7rem 0;
  }
  .remember {
    display: flex;
    gap: 0.5rem;
    align-items: center;
  }
  form {
    display: flex;
    flex-wrap: wrap;
    gap: 0.6rem;
  }
  form :global(input) {
    min-width: min(100%, 12rem);
    flex: 1 1 12rem;
  }
  p {
    color: var(--muted-foreground);
  }
  [role='alert'] {
    color: var(--destructive);
  }
</style>

// apps/web/src/snippets-react/destination-picker.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, Button, Input, AppNav, DynamicComponent, Dialog, Menu, ReaderScope, useLatest, useReaderBindings, type ReaderViewProps } from './primitives';
import { createDestinationPicker, type DestinationPickerProps } from './destination-picker-controller';
import { resolve } from '$app/paths';
import { sourceDescriptors, type SourceDescriptor } from '../lib/library/catalog';
import { providerLabels, requestDocumentWriteAccess } from '../lib/manabi/client';
import { integrationDB } from '../lib/manabi/persistence';
import { reconnectLocalLibrary } from '../lib/manabi/sources';
import type { Destination, Guard } from '../lib/snippets/database';
import { capability, folders, makeFolder, type StorageCapability } from '../lib/snippets/storage';



export function DestinationPicker(props: DestinationPickerProps & ReaderViewProps) {
const latest = useLatest(props);
const c = useReaderController(() => createDestinationPicker(props as DestinationPickerProps, (name, detail) => latest.current.events?.[name]?.({ detail })), props);
useReaderBindings(c, props);
if (!c) return null;
return <ReaderScope name="react-snippets-destination-picker">
<Dom scopeClass="snippet-scope-destination-picker" as="div" className={["destination-picker"].filter(Boolean).join(' ')}>
<Dom scopeClass="snippet-scope-destination-picker" as="p" >{" Save the document in one connected location. Collections and reading history stay attached when it moves. "}</Dom>
<Dom scopeClass="snippet-scope-destination-picker" as="label" >{"Storage source "}<Dom scopeClass="snippet-scope-destination-picker" as="select" aria-label={"Storage source"}
disabled={c.granting}
value={c.selected ? c.identity(c.selected) : ''}
onChange={(event) => {
    const source = c.sources.find((item) => c.identity(item) === event.currentTarget.value);
    if (source)
        void c.browse(source, source.root, source.name, true);
}}
className={["control-select min-h-11"].filter(Boolean).join(' ')}>
<Dom scopeClass="snippet-scope-destination-picker" as="option" value={""}
disabled={true}>{"Choose a source"}</Dom>
{(c.sources ?? []).length ? (c.sources ?? []).map((source, index0) => <React.Fragment key={c.identity(source)}><Dom scopeClass="snippet-scope-destination-picker" as="option" value={c.identity(source)}>{c.providerName(source.provider)}{" · "}{source.name}</Dom></React.Fragment>) : null}
</Dom>
</Dom>
{(c.selected) ? <><Dom scopeClass="snippet-scope-destination-picker" as="nav" aria-label={"Destination folder"}
elementRef={(value) => { c.trailNav = value; }}
className={["breadcrumbs"].filter(Boolean).join(' ')}>
{(c.trail ?? []).length ? (c.trail ?? []).map((part, index) => <React.Fragment key={part.id}><Button  variant={"link"}
size={"sm"}
aria-current={index === c.trail.length - 1 ? 'page' : undefined}
disabled={c.busy}
onClick={() => {
    c.trail = c.trail.slice(0, index);
    void c.navigate(c.selected!, part.id, part.name);
}}
className={["min-h-11 px-1"].filter(Boolean).join(' ')}>{part.name || 'Root'}</Button>
{(index < c.trail.length - 1) ? <><Dom scopeClass="snippet-scope-destination-picker" as="span" aria-hidden={"true"}>{"›"}</Dom></> : null}</React.Fragment>) : null}
</Dom>
<Dom scopeClass="snippet-scope-destination-picker" as="div" aria-busy={c.busy}
className={["folder-list"].filter(Boolean).join(' ')}>
{(c.entries ?? []).length ? (c.entries ?? []).map((folder, index1) => <React.Fragment key={folder.id}><Button  variant={"ghost"}
shape={"rounded"}
disabled={c.busy}
onClick={() => c.navigate(c.selected!, folder.id, folder.name)}
className={["min-h-11 w-full justify-start px-3 text-left"].filter(Boolean).join(' ')}>
<Icon name="FolderOpen" aria-hidden={"true"}
className={["size-4 shrink-0"].filter(Boolean).join(' ')}></Icon>
<Dom scopeClass="snippet-scope-destination-picker" as="span" className={["min-w-0 break-words"].filter(Boolean).join(' ')}>{folder.name}</Dom>
</Button></React.Fragment>) : <> <Dom scopeClass="snippet-scope-destination-picker" as="p" >
{c.busy ? 'Loading folders…'
    : c.ready ? 'No subfolders.'
        : 'This folder could not be loaded.'}
</Dom></>}
</Dom>
{(c.selected.provider === 'local') ? <><Dom scopeClass="snippet-scope-destination-picker" as="p" >{" Close other applications editing these files before saving. This browser cannot lock out external file editors. "}</Dom></> : null}
{(c.capabilities?.write && c.ready) ? <><Dom scopeClass="snippet-scope-destination-picker" as="form" onSubmit={(event) => {
    event.preventDefault();
    void c.mkdir();
}}>
<Input  aria-label={"New folder name"}
placeholder={"New folder name"}
value={c.newName}
maxLength={100}
className={["min-h-11"].filter(Boolean).join(' ')}
bindings={{"value": (value) => { c.newName = value; }}}></Input>
<Button  type={"submit"}
variant={"secondary"}
disabled={c.busy || !c.newName.trim()}>{"Create folder"}</Button>
</Dom>
<Dom scopeClass="snippet-scope-destination-picker" as="label" className={["remember"].filter(Boolean).join(' ')}><Dom scopeClass="snippet-scope-destination-picker" as="input" type={"checkbox"}
checked={c.remember}
className={["size-5 accent-primary"].filter(Boolean).join(' ')}
bindings={{"checked": (value) => { c.remember = value; }}} />{" Use this location for new snippets"}</Dom>
<Button  disabled={c.busy}
onClick={c.useFolder}>{"Use this folder"}</Button></> : <> {(c.capabilities && !c.capabilities.write) ? <><Dom scopeClass="snippet-scope-destination-picker" as="p" >
{c.capabilities.reason ||
    'This source is read-only. Authorize document editing to save here.'}
</Dom>
{(c.selected.provider !== 'webdav' && !c.capabilities.reason && !c.permissionRequired) ? <><Button  disabled={c.busy}
onClick={c.grant}>{"Allow document editing"}</Button></> : null}
{(c.selected.provider === 'google') ? <><Dom scopeClass="snippet-scope-destination-picker" as="p" >{" Google will request access to files in your Drive so Manabi can edit documents inside your selected library folders. "}</Dom></> : null}</> : null}</>}</> : null}
{(c.permissionRequired) ? <><Button  disabled={c.busy}
onClick={c.grant}>{"Allow folder access"}</Button></> : null}
{(c.error && c.selected && !c.permissionRequired) ? <><Button  variant={"secondary"}
disabled={c.busy}
onClick={() => c.browse(c.selected!, c.parent, c.trail.at(-1)?.name, true)}>{" Retry folder "}</Button></> : null}
{(c.allowDevice) ? <><Button  variant={"ghost"}
onClick={() => c.choose(undefined, false)}>{"Keep on this device only"}</Button></> : null}
{(c.allowUnsetDefault) ? <><Button  variant={"ghost"}
onClick={() => c.choose(undefined, false)}>{"Clear default location"}</Button></> : null}
<Button  href={resolve('/connections')}
variant={"link"}
size={"sm"}
className={["min-h-11 justify-start px-0"].filter(Boolean).join(' ')}>{"Manage connected libraries"}</Button>
{(c.error) ? <><Dom scopeClass="snippet-scope-destination-picker" as="p" role={"alert"}>{c.error}</Dom></> : null}
</Dom>
</ReaderScope>;
}
