// apps/web/src/statistics-react/statistics-title-filter.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  Button,
  CloseButton,
  Sheet,
  useLatest,
  useReaderBindings,
  type ReaderViewProps,
  Input,
  ReaderScope
} from './primitives';
import {
  createStatisticsTitleFilter,
  type StatisticsTitleFilterProps
} from './statistics-title-filter-controller';
import { stickyPanel } from '$lib/hooks/sticky-panel';

export function StatisticsTitleFilter(
  props: Partial<StatisticsTitleFilterProps> & ReaderViewProps
) {
  const latest = useLatest(props);
  const c = useReaderController(
    () =>
      createStatisticsTitleFilter(props as StatisticsTitleFilterProps, (name, detail) =>
        latest.current.events?.[name]?.({ detail })
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <ReaderScope name="react-statistics-statistics-title-filter">
      <Dom
        as="div"
        className={['filter-panel'].filter(Boolean).join(' ')}
        actions={[[stickyPanel, undefined]]}
      >
        <Dom
          as="div"
          data-sticky-header={true}
          className={['filter-header'].filter(Boolean).join(' ')}
        >
          <Sheet.Title className={['min-w-0 text-xl font-semibold'].filter(Boolean).join(' ')}>
            {'Filter books'}
          </Sheet.Title>
          <CloseButton
            aria-label={'Close title filter'}
            onClick={() => c.dispatch('close')}
          ></CloseButton>
        </Dom>
        <Input
          type={'search'}
          placeholder={'Filter titles'}
          aria-label={'Filter book titles'}
          value={c.titleFilter}
          onInput={(event) => {
            c.titleFilter = event.currentTarget.value;
            c.page = 1;
          }}
        ></Input>
        <Dom
          as="div"
          role={'group'}
          aria-label={'Title visibility'}
          className={['flex flex-wrap gap-2'].filter(Boolean).join(' ')}
        >
          <Button
            variant={c.$lastStatisticsFilterDateRangeOnly$ ? 'secondary' : 'ghost'}
            shape={'rounded'}
            aria-pressed={c.$lastStatisticsFilterDateRangeOnly$}
            onClick={() => {
              c.$lastStatisticsFilterDateRangeOnly$ = !c.$lastStatisticsFilterDateRangeOnly$;
              c.page = 1;
            }}
          >
            {'Selected dates only'}
          </Button>
          <Button
            variant={c.$lastStatisticsFilterShowSelectedTitlesOnly$ ? 'secondary' : 'ghost'}
            shape={'rounded'}
            aria-pressed={c.$lastStatisticsFilterShowSelectedTitlesOnly$}
            onClick={() => {
              c.$lastStatisticsFilterShowSelectedTitlesOnly$ =
                !c.$lastStatisticsFilterShowSelectedTitlesOnly$;
              c.page = 1;
            }}
          >
            {'Selected titles only'}
          </Button>
        </Dom>
        <Dom as="div" className={['flex flex-wrap items-center gap-2'].filter(Boolean).join(' ')}>
          <Button
            variant={'ghost'}
            disabled={!c.filteredTitles.length}
            onClick={() => c.selectMatching(true)}
          >
            {'Select matching'}
          </Button>
          <Button
            variant={'ghost'}
            disabled={!c.filteredTitles.length}
            onClick={() => c.selectMatching(false)}
          >
            {'Remove matching'}
          </Button>
          {c.$preFilteredTitlesForStatistics$.size || c.$preFilteredBookKeysForStatistics$.size ? (
            <>
              <Button variant={'outline'} onClick={() => c.dispatch('clearPrefilter')}>
                {'Remove Prefilter'}
              </Button>
            </>
          ) : null}
        </Dom>
        <Dom
          as="p"
          role={'status'}
          className={['text-sm text-muted-foreground'].filter(Boolean).join(' ')}
        >
          {c.filteredTitles.length}
          {' matching titles · '}
          {c.titlesToFilter.filter((item) => item.isSelected).length}
          {' selected '}
        </Dom>
        {c.current.rows.length ? (
          <>
            <Dom
              as="div"
              elementRef={(value) => {
                c.titleList = value;
              }}
              role={'group'}
              aria-label={'Book title selection'}
              className={['title-list'].filter(Boolean).join(' ')}
            >
              {(c.current.rows ?? []).map((item, index0) => (
                <React.Fragment key={item.title}>
                  <Dom as="label" className={['title-row'].filter(Boolean).join(' ')}>
                    <Dom
                      as="input"
                      type={'checkbox'}
                      aria-label={item.title}
                      checked={item.isSelected}
                      onChange={(event) => c.selectTitle(item.title, event.currentTarget.checked)}
                    />
                    <Dom
                      as="span"
                      className={[
                        !c.titlesInStatisticsDateRange.has(item.title) && 'text-muted-foreground'
                      ]
                        .filter(Boolean)
                        .join(' ')}
                    >
                      {item.title}
                    </Dom>
                  </Dom>
                </React.Fragment>
              ))}
            </Dom>
          </>
        ) : (
          <>
            {' '}
            <Dom
              as="p"
              className={['rounded-xl bg-muted p-5 text-center'].filter(Boolean).join(' ')}
            >
              {'No Titles to filter'}
            </Dom>
          </>
        )}
        {c.current.pages > 1 ? (
          <>
            <Dom
              as="div"
              aria-label={'Title pages'}
              className={['flex flex-wrap items-center justify-between gap-2']
                .filter(Boolean)
                .join(' ')}
            >
              <Button
                variant={'ghost'}
                disabled={c.current.page === 1}
                onClick={() => c.changePage(c.current.page - 1)}
              >
                {'Previous'}
              </Button>
              <Dom
                as="span"
                className={['text-sm text-muted-foreground'].filter(Boolean).join(' ')}
              >
                {'Page '}
                {c.current.page}
                {' / '}
                {c.current.pages}
              </Dom>
              <Button
                variant={'ghost'}
                disabled={c.current.page === c.current.pages}
                onClick={() => c.changePage(c.current.page + 1)}
              >
                {'Next'}
              </Button>
            </Dom>
          </>
        ) : null}
        <Dom
          as="div"
          data-sticky-footer={true}
          className={['filter-footer'].filter(Boolean).join(' ')}
        >
          <Button variant={'ghost'} onClick={() => c.dispatch('close')}>
            {'Cancel'}
          </Button>
          <Button
            variant={'secondary'}
            onClick={() => {
              c.dispatch('applyFilter', c.titlesToFilter);
              c.dispatch('close');
            }}
          >
            {'Apply Filter'}
          </Button>
        </Dom>
      </Dom>
    </ReaderScope>
  );
}

// apps/web/src/lib/components/statistics/statistics-title-filter.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import * as Sheet from '$lib/components/ui/sheet';
  import { Button } from '$lib/components/ui/button';
  import CloseButton from '$lib/components/ui/close-button.svelte';
  import { Input } from '$lib/components/ui/input';
  import {
    preFilteredTitlesForStatistics$,
    type StatisticsTitleFilterItem
  } from './statistics-types';
  import {
    lastStatisticsFilterDateRangeOnly$,
    lastStatisticsFilterShowSelectedTitlesOnly$,
    skipKeyDownListener$
  } from '$lib/data/store';
  import { filterStatisticsTitles, statisticsTitlePage } from './title-filter-model';

  export let statisticsTitleFilters: Map<string, boolean>;
  export let titlesInStatisticsDateRange: Set<string>;

  const dispatch = createEventDispatcher<{
    applyFilter: StatisticsTitleFilterItem[];
    clearPrefilter: void;
    close: void;
  }>();
  let titleFilter = '';
  let page = 1;
  let titlesToFilter: StatisticsTitleFilterItem[] = [];
  // Draft selection is private to this opening. Close/Escape never applies it.
  $: titlesToFilter = [...statisticsTitleFilters].map(([title, isSelected]) => ({
    title,
    isSelected
  }));
  $: filteredTitles = filterStatisticsTitles(
    titlesToFilter,
    titleFilter,
    titlesInStatisticsDateRange,
    $lastStatisticsFilterDateRangeOnly$,
    $lastStatisticsFilterShowSelectedTitlesOnly$
  );
  $: current = statisticsTitlePage(filteredTitles, page);

  onMount(() => {
    $skipKeyDownListener$ = true;
    return () => {
      $skipKeyDownListener$ = false;
    };
  });

  function selectTitle(title: string, isSelected: boolean) {
    titlesToFilter = titlesToFilter.map((item) =>
      item.title === title ? { ...item, isSelected } : item
    );
    page = current.page;
  }

  function selectAll(isSelected: boolean) {
    titlesToFilter = titlesToFilter.map((item) => ({ ...item, isSelected }));
    page = 1;
  }
</script>

<div class="filter-panel">
  <div class="flex items-start justify-between gap-3">
    <Sheet.Title class="min-w-0 text-xl font-semibold">Filter books</Sheet.Title>
    <CloseButton aria-label="Close title filter" onclick={() => dispatch('close')} />
  </div>
  <Input
    type="search"
    placeholder="Filter titles"
    aria-label="Filter book titles"
    value={titleFilter}
    oninput={(event) => {
      titleFilter = event.currentTarget.value;
      page = 1;
    }}
  />
  <div class="flex flex-wrap gap-2" role="group" aria-label="Title visibility">
    <Button
      variant={$lastStatisticsFilterDateRangeOnly$ ? 'secondary' : 'ghost'}
      shape="rounded"
      aria-pressed={$lastStatisticsFilterDateRangeOnly$}
      onclick={() => {
        $lastStatisticsFilterDateRangeOnly$ = !$lastStatisticsFilterDateRangeOnly$;
        page = 1;
      }}>Selected dates only</Button
    >
    <Button
      variant={$lastStatisticsFilterShowSelectedTitlesOnly$ ? 'secondary' : 'ghost'}
      shape="rounded"
      aria-pressed={$lastStatisticsFilterShowSelectedTitlesOnly$}
      onclick={() => {
        $lastStatisticsFilterShowSelectedTitlesOnly$ =
          !$lastStatisticsFilterShowSelectedTitlesOnly$;
        page = 1;
      }}>Selected titles only</Button
    >
  </div>
  <div class="flex flex-wrap items-center gap-2">
    <Button variant="ghost" onclick={() => selectAll(true)}>Select All</Button>
    <Button variant="ghost" onclick={() => selectAll(false)}>Remove All</Button>
    {#if $preFilteredTitlesForStatistics$.size}
      <Button variant="outline" onclick={() => dispatch('clearPrefilter')}>Remove Prefilter</Button>
    {/if}
  </div>
  <p role="status" class="text-sm text-muted-foreground">
    {filteredTitles.length} matching titles · {titlesToFilter.filter((item) => item.isSelected).length} selected
  </p>
  {#if current.rows.length}
    <div class="title-list" role="group" aria-label="Book title selection">
      {#each current.rows as item (item.title)}
        <label class="title-row">
          <input
            type="checkbox"
            aria-label={item.title}
            checked={item.isSelected}
            onchange={(event) => selectTitle(item.title, event.currentTarget.checked)}
          />
          <span class:text-muted-foreground={!titlesInStatisticsDateRange.has(item.title)}
            >{item.title}</span
          >
        </label>
      {/each}
    </div>
  {:else}
    <p class="rounded-xl bg-muted p-5 text-center">No Titles to filter</p>
  {/if}
  {#if current.pages > 1}
    <div class="flex flex-wrap items-center justify-between gap-2" aria-label="Title pages">
      <Button
        variant="ghost"
        disabled={current.page === 1}
        onclick={() => (page = current.page - 1)}>Previous</Button
      >
      <span class="text-sm text-muted-foreground">Page {current.page} / {current.pages}</span>
      <Button
        variant="ghost"
        disabled={current.page === current.pages}
        onclick={() => (page = current.page + 1)}>Next</Button
      >
    </div>
  {/if}
  <div class="flex flex-wrap justify-end gap-2 border-t border-border pt-4">
    <Button variant="ghost" onclick={() => dispatch('close')}>Cancel</Button>
    <Button
      variant="secondary"
      onclick={() => {
        dispatch('applyFilter', titlesToFilter);
        dispatch('close');
      }}>Apply Filter</Button
    >
  </div>
</div>

<style>
  .filter-panel {
    display: grid;
    flex-shrink: 0;
    min-width: 0;
    gap: 16px;
    padding: 20px;
    padding-bottom: max(20px, env(safe-area-inset-bottom));
  }
  .title-list {
    overflow: hidden;
    border: 1px solid var(--border);
    border-radius: 12px;
  }
  .title-row {
    display: flex;
    min-height: 52px;
    align-items: center;
    gap: 12px;
    padding: 12px;
    cursor: pointer;
  }
  .title-row + .title-row {
    border-top: 1px solid var(--border);
  }
  .title-row:hover,
  .title-row:focus-within {
    background: var(--muted);
  }
  .title-row input {
    flex-shrink: 0;
    width: 20px;
    height: 20px;
    accent-color: var(--primary);
  }
  .title-row span {
    min-width: 0;
    overflow-wrap: anywhere;
  }
</style>
