// apps/web/src/lib/components/settings/settings-sync-dialog.svelte
<script lang="ts">
  import faArrowsUpDown from '@lucide/svelte/icons/move-vertical';
  import DialogTemplate from '$lib/components/dialog-template.svelte';
  import { Button } from '$lib/components/ui/button';
  import { InternalStorageSources, StorageKey } from '$lib/data/storage/storage-types';
  import type { BooksDbStorageSource } from '$lib/data/database/books-db/versions/books-db';
  import type { SyncSelection } from '$lib/data/dialog-manager';
  import { lastSyncedSettingsSource$, lastSyncedSettingsTarget$ } from '$lib/data/store';
  import { createEventDispatcher } from 'svelte';
  import AppIcon from '$lib/components/app-icon.svelte';

  export let settingsSyncHeader = '';
  export let storageSources: BooksDbStorageSource[] = [];
  export let resolver: (arg0: SyncSelection[]) => void;

  const dispatch = createEventDispatcher<{
    close: void;
  }>();

  const syncSources: SyncSelection[] = [
    { id: InternalStorageSources.INTERNAL_BROWSER, label: 'Browser DB', type: StorageKey.BROWSER },
    { id: InternalStorageSources.INTERNAL_ZIP, label: 'ZIP File', type: StorageKey.BACKUP },
    ...storageSources.map((storageSource) => ({
      id: storageSource.name,
      label: `${storageSource.name} (${storageSource.type})`,
      type: storageSource.type
    }))
  ];

  let selectedSource =
    syncSources.find((entry) => entry.id === $lastSyncedSettingsSource$)?.id || syncSources[0].id;
  let selectedTarget =
    syncSources.find((entry) => entry.id === $lastSyncedSettingsTarget$)?.id || syncSources[1].id;

  $: sources = syncSources.filter(
    (entry) => entry.id !== selectedTarget && entry.id !== InternalStorageSources.INTERNAL_ZIP
  );
  $: targets = syncSources.filter((entry) => entry.id !== selectedSource);

  function closeDialog(wasCanceled = false) {
    if (!wasCanceled) {
      $lastSyncedSettingsSource$ = selectedSource;
      $lastSyncedSettingsTarget$ = selectedTarget;
    }

    resolver(
      wasCanceled
        ? []
        : [
            syncSources.find((entry) => entry.id === selectedSource)!,
            syncSources.find((entry) => entry.id === selectedTarget)!
          ]
    );
    dispatch('close');
  }
</script>

<DialogTemplate>
  <svelte:fragment slot="header">{settingsSyncHeader}</svelte:fragment>
  <svelte:fragment slot="content">
    <div class="grid gap-4">
      <label class="grid gap-2 text-sm font-medium">
        <span>Source</span>
        <select
          class="min-h-11 min-w-0 rounded-[10px] border border-input bg-background px-3 py-2 text-base text-foreground outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 md:text-sm"
          bind:value={selectedSource}
        >
          {#each sources as source (source.id)}
            <option value={source.id}>
              {source.label}
            </option>
          {/each}
        </select>
      </label>
      <Button
        variant="ghost"
        size="icon"
        shape="circle"
        class="justify-self-center"
        aria-label="Swap sync source and target"
        title={selectedTarget === InternalStorageSources.INTERNAL_ZIP
          ? 'Choose a different target before swapping'
          : 'Swap source and target'}
        disabled={selectedTarget === InternalStorageSources.INTERNAL_ZIP}
        onclick={() => {
          const oldSource = selectedSource;
          const oldTarget = selectedTarget;

          selectedSource = oldTarget;
          selectedTarget = oldSource;
        }}
      >
        <AppIcon icon={faArrowsUpDown} />
      </Button>
      <label class="grid gap-2 text-sm font-medium">
        <span>Target</span>
        <select
          class="min-h-11 min-w-0 rounded-[10px] border border-input bg-background px-3 py-2 text-base text-foreground outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 md:text-sm"
          bind:value={selectedTarget}
        >
          {#each targets as target (target.id)}
            <option value={target.id}>
              {target.label}
            </option>
          {/each}
        </select>
      </label>
    </div>
  </svelte:fragment>
  <div class="flex grow flex-wrap justify-between gap-2" slot="footer">
    <Button variant="ghost" onclick={() => closeDialog(true)}>Cancel</Button>
    <Button variant="default" onclick={() => closeDialog()}>Confirm</Button>
  </div>
</DialogTemplate>

// apps/web/src/settings-react/settings-sync-dialog.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, AppIcon, Button, Input, Switch, Field, Popover, DialogTemplate, ActionMenu, AppNav, Menu, useLatest, useReaderBindings, slotContent, Slot, type ReaderViewProps } from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import { createSettingsSyncDialog, type SettingsSyncDialogProps } from './settings-sync-dialog-controller';
import { InternalStorageSources, StorageKey } from '$lib/data/storage/storage-types';
import type { BooksDbStorageSource } from '$lib/data/database/books-db/versions/books-db';
import type { SyncSelection } from '$lib/data/dialog-manager';
import { lastSyncedSettingsSource$, lastSyncedSettingsTarget$ } from '$lib/data/store';
const faArrowsUpDown = 'faArrowsUpDown';
export function SettingsSyncDialog(props: Partial<SettingsSyncDialogProps> & ReaderViewProps & {
    children?: React.ReactNode;
    onClose?: () => void;
    slot?: string;
}) {
    const latest = useLatest(props);
    const context = useSettingsContext();
    const c = useReaderController(() => createSettingsSyncDialog(props as SettingsSyncDialogProps, (name, detail) => { latest.current.events?.[name]?.({ detail }); if (name === 'close')
        latest.current.onClose?.(); }, context), props);
    useReaderBindings(c, props);
    if (!c)
        return null;
    return <SettingsContext.Provider value={context}><div className="react-settings-settings-sync-dialog" style={{ display: 'contents' }}>
    <DialogTemplate>
    <Slot name="header">{c.settingsSyncHeader}</Slot>
    <Slot name="content">
    <Dom as="div" className={["grid gap-4"].filter(Boolean).join(' ')}>
    <Dom as="label" className={["grid gap-2 text-sm font-medium"].filter(Boolean).join(' ')}>
    <Dom as="span">{"Source"}</Dom>
    <Dom as="select" value={c.selectedSource} className={["min-h-11 min-w-0 rounded-[10px] border border-input bg-background px-3 py-2 text-base text-foreground outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 md:text-sm"].filter(Boolean).join(' ')} bindings={{ "value": (value) => { c.controller.changed(c.selectedSource = value); } }}>
        {(c.sources ?? []).map((source, index0) => <React.Fragment key={source.id}><Dom as="option" value={source.id}>
        {source.label}
        </Dom></React.Fragment>)}
    </Dom>
    </Dom>
    <Button variant={"ghost"} size={"icon"} shape={"circle"} aria-label={"Swap sync source and target"} title={c.selectedTarget === InternalStorageSources.INTERNAL_ZIP
            ? 'Choose a different target before swapping'
            : 'Swap source and target'} disabled={c.selectedTarget === InternalStorageSources.INTERNAL_ZIP} onClick={() => {
            const oldSource = c.selectedSource;
            const oldTarget = c.selectedTarget;
            c.controller.changed(c.selectedSource = oldTarget);
            c.controller.changed(c.selectedTarget = oldSource);
        }} className={["justify-self-center"].filter(Boolean).join(' ')}>
    <AppIcon icon={faArrowsUpDown}></AppIcon>
    </Button>
    <Dom as="label" className={["grid gap-2 text-sm font-medium"].filter(Boolean).join(' ')}>
    <Dom as="span">{"Target"}</Dom>
    <Dom as="select" value={c.selectedTarget} className={["min-h-11 min-w-0 rounded-[10px] border border-input bg-background px-3 py-2 text-base text-foreground outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 md:text-sm"].filter(Boolean).join(' ')} bindings={{ "value": (value) => { c.controller.changed(c.selectedTarget = value); } }}>
        {(c.targets ?? []).map((target, index1) => <React.Fragment key={target.id}><Dom as="option" value={target.id}>
        {target.label}
        </Dom></React.Fragment>)}
    </Dom>
    </Dom>
    </Dom>
    </Slot>
    <Dom as="div" slot={"footer"} className={["flex grow flex-wrap justify-between gap-2"].filter(Boolean).join(' ')}>
    <Button variant={"ghost"} onClick={() => c.closeDialog(true)}>{"Cancel"}</Button>
    <Button variant={"default"} onClick={() => c.closeDialog()}>{"Confirm"}</Button>
    </Dom>
    </DialogTemplate></div></SettingsContext.Provider>;
}
