// apps/web/src/lib/components/settings/settings-custom-theme-input.svelte
<script lang="ts">
  import { Input } from '$lib/components/ui/input';
  import type { CustomThemeValue, ThemeOption } from '$lib/data/theme-option';
  import { createEventDispatcher } from 'svelte';

  export let label: string;
  export let attribute: keyof ThemeOption;
  export let values: CustomThemeValue;

  const dispatch = createEventDispatcher<{
    color: { attribute: keyof ThemeOption; value: string };
    alpha: { attribute: keyof ThemeOption; value: number };
  }>();

  function handleColorChange(event: Event) {
    const target = event.target as HTMLInputElement;

    dispatch('color', { attribute, value: target.value });
  }

  function handleAlphaChange(event: Event) {
    const target = event.target as HTMLInputElement;

    let value = target.value ? parseFloat(target.value) : undefined;

    if (!Number.isFinite(value) || value === undefined || value < 0 || value > 1) {
      value = 1;
      target.value = '1';
    }

    dispatch('alpha', { attribute, value });
  }
</script>

<span>{label}</span>
<input
  aria-label={`${label} color`}
  type="color"
  class="size-11 rounded-xl border border-border bg-background p-1"
  value={values.hexExpression}
  on:change={handleColorChange}
/>
<Input
  aria-label={`${label} opacity`}
  class="min-h-11"
  type="number"
  step="0.1"
  min="0"
  max="1"
  value={values.alphaValue}
  onchange={handleAlphaChange}
/>

// apps/web/src/settings-react/settings-custom-theme-input.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, AppIcon, Button, Input, Switch, Field, Popover, DialogTemplate, ActionMenu, AppNav, Menu, useLatest, useReaderBindings, slotContent, Slot, type ReaderViewProps } from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import { createSettingsCustomThemeInput, type SettingsCustomThemeInputProps } from './settings-custom-theme-input-controller';
import type { CustomThemeValue, ThemeOption } from '$lib/data/theme-option';
export function SettingsCustomThemeInput(props: Partial<SettingsCustomThemeInputProps> & ReaderViewProps & {
    children?: React.ReactNode;
    onClose?: () => void;
    slot?: string;
}) {
    const latest = useLatest(props);
    const context = useSettingsContext();
    const c = useReaderController(() => createSettingsCustomThemeInput(props as SettingsCustomThemeInputProps, (name, detail) => { latest.current.events?.[name]?.({ detail }); if (name === 'close')
        latest.current.onClose?.(); }, context), props);
    useReaderBindings(c, props);
    if (!c)
        return null;
    return <SettingsContext.Provider value={context}><div className="react-settings-settings-custom-theme-input" style={{ display: 'contents' }}>
    <Dom as="span">{c.label}</Dom>
    <Dom as="input" aria-label={`${c.label} color`} type={"color"} value={c.values.hexExpression} className={["size-11 rounded-xl border border-border bg-background p-1"].filter(Boolean).join(' ')} events={{ "change": c.handleColorChange }}/>
    <Input aria-label={`${c.label} opacity`} type={"number"} step={"0.1"} min={"0"} max={"1"} value={c.values.alphaValue} onChange={c.handleAlphaChange} className={["min-h-11"].filter(Boolean).join(' ')}></Input></div></SettingsContext.Provider>;
}
