// apps/web/src/lib/components/settings/settings-user-font-dialog.svelte
<script lang="ts">
  import DialogTemplate from '$lib/components/dialog-template.svelte';
  import SettingsUserFontAdd from '$lib/components/settings/settings-user-font-add.svelte';
  import { Button } from '$lib/components/ui/button';
  import { userFontsCacheName, type UserFont } from '$lib/data/fonts';
  import { userFonts$ } from '$lib/data/store';
  import type { BehaviorSubject } from 'rxjs';
  import { createEventDispatcher, onMount } from 'svelte';
  import { fontActionError, removeUserFont, sameUserFont, storedFontPaths } from './user-font-actions';

  export let fontFamily: BehaviorSubject<string>;

  const dispatch = createEventDispatcher<{ close: void }>();
  let isLoading = false;
  let cacheLoaded = false;
  let currentTab = 'Stored';
  let fontCache: Cache | undefined;
  let availablePaths = new Set<string>();
  let error = '';
  let alive = false;
  let loadGeneration = 0;

  onMount(() => {
    alive = true;
    void loadCache();
    return () => { alive = false; loadGeneration += 1; };
  });

  async function loadCache() {
    const generation = ++loadGeneration;
    cacheLoaded = false;
    error = '';
    try {
      const cache = await caches.open(userFontsCacheName);
      const paths = await storedFontPaths(cache);
      if (!alive || generation !== loadGeneration) return;
      fontCache = cache;
      availablePaths = paths;
    } catch (cause) {
      if (!alive || generation !== loadGeneration) return;
      fontCache = undefined;
      error = fontActionError(cause);
    } finally {
      if (alive && generation === loadGeneration) cacheLoaded = true;
    }
  }

  async function selectFont(target: UserFont) {
    if (!alive || isLoading || !fontCache) return;
    const font = { ...target };
    const family = fontFamily;
    isLoading = true;
    error = '';
    try {
      const present = await fontCache.match(font.path);
      if (!alive || family !== fontFamily) return;
      if (!present || !$userFonts$.some((entry) => sameUserFont(entry, font))) {
        error = 'This font file is no longer available. Add it again to use it.';
        availablePaths = new Set([...availablePaths].filter((path) => path !== font.path));
        return;
      }
      family.next(font.name);
      dispatch('close');
    } catch (cause) {
      if (alive) error = fontActionError(cause);
    } finally {
      if (alive) isLoading = false;
    }
  }

  async function removeFont(path: string) {
    const target = $userFonts$.find((entry) => entry.path === path);
    if (!target) return;
    if (!alive || isLoading || !fontCache) return;
    const family = fontFamily;
    isLoading = true;
    error = '';
    try {
      await removeUserFont(
        fontCache,
        { read: () => userFonts$.getValue(), write: (fonts) => userFonts$.next(fonts) },
        target,
        { read: () => family.getValue(), write: (name) => family.next(name) }
      );
      if (alive) await loadCache();
    } catch (cause) {
      if (alive) error = fontActionError(cause);
    } finally {
      if (alive) isLoading = false;
    }
  }
</script>

<DialogTemplate>
  <svelte:fragment slot="header">Custom fonts</svelte:fragment>
  <div slot="content" class="font-manager min-w-0 space-y-4" aria-busy={isLoading || !cacheLoaded}>
    <p class="text-sm text-muted-foreground">Manage fonts stored in this browser. Choose a font to use it for this text style.</p>
    <div class="section-navigation" role="group" aria-label="Custom font views">
      {#each ['Stored', 'Add'] as tab (tab)}
        <Button
          variant="ghost"
          shape="rounded"
          data-section-link
          class="min-h-11"
          aria-pressed={currentTab === tab}
          disabled={isLoading || !fontCache}
          onclick={() => (currentTab = tab)}>{tab === 'Add' ? 'Add font' : 'Stored fonts'}</Button>
      {/each}
    </div>
    {#if error}<p role="alert" class="break-words text-sm text-destructive">{error}</p>{/if}
    {#if !cacheLoaded}
      <p role="status" class="text-sm text-muted-foreground">Checking font storage…</p>
    {:else if !fontCache}
      <p class="text-sm text-muted-foreground">Your saved font list has not been changed.</p>
      <Button variant="outline" onclick={loadCache}>Retry font storage</Button>
    {:else if currentTab === 'Stored'}
      {#if $userFonts$.length}
        <ul class="divide-y divide-border" aria-label="Stored custom fonts">
          {#each $userFonts$ as userFont (userFont.path)}
            <li class="flex min-w-0 flex-wrap items-center gap-3 py-3">
              <div class="min-w-0 flex-1 basis-40">
                <p class="break-words font-medium">{userFont.name}</p>
                <p class="break-words text-xs text-muted-foreground">{userFont.fileName}</p>
                {#if !availablePaths.has(userFont.path)}
                  <p class="mt-1 text-xs text-muted-foreground">File unavailable. Remove this entry, then add the file again.</p>
                {/if}
              </div>
              <div class="flex flex-wrap gap-2">
                <Button variant="outline" class="min-h-11" disabled={isLoading || !availablePaths.has(userFont.path)} aria-label={`Use ${userFont.name}`} onclick={() => selectFont(userFont)}>Use font</Button>
                <Button variant="destructive" class="min-h-11" disabled={isLoading} aria-label={`Remove ${userFont.name}`} onclick={() => removeFont(userFont.path)}>Remove</Button>
              </div>
            </li>
          {/each}
        </ul>
      {:else}
        <p class="rounded-2xl bg-muted p-4 text-sm text-muted-foreground">No custom fonts yet. Add a font file to make it available here.</p>
      {/if}
      {#if isLoading}<p role="status" class="text-sm text-muted-foreground">Updating fonts…</p>{/if}
    {:else}
      <SettingsUserFontAdd {fontCache} bind:isLoading on:saved={() => { currentTab = 'Stored'; void loadCache(); }} />
    {/if}
  </div>
  <svelte:fragment slot="footer"><Button variant="ghost" class="min-h-11" onclick={() => dispatch('close')}>Done</Button></svelte:fragment>
</DialogTemplate>

<style>
  .font-manager { overflow-wrap: anywhere; }
</style>

// apps/web/src/settings-react/settings-user-font-dialog.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, AppIcon, Button, Input, Switch, Field, Popover, DialogTemplate, ActionMenu, AppNav, Menu, useLatest, useReaderBindings, slotContent, Slot, type ReaderViewProps } from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import { createSettingsUserFontDialog, type SettingsUserFontDialogProps } from './settings-user-font-dialog-controller';
import { userFontsCacheName, type UserFont } from '$lib/data/fonts';
import { userFonts$ } from '$lib/data/store';
import type { BehaviorSubject } from 'rxjs';
import { fontActionError, removeUserFont, sameUserFont, storedFontPaths } from '../lib/components/settings/user-font-actions';
import { SettingsUserFontAdd } from './settings-user-font-add';
export function SettingsUserFontDialog(props: Partial<SettingsUserFontDialogProps> & ReaderViewProps & {
    children?: React.ReactNode;
    onClose?: () => void;
    slot?: string;
}) {
    const latest = useLatest(props);
    const context = useSettingsContext();
    const c = useReaderController(() => createSettingsUserFontDialog(props as SettingsUserFontDialogProps, (name, detail) => { latest.current.events?.[name]?.({ detail }); if (name === 'close')
        latest.current.onClose?.(); }, context), props);
    useReaderBindings(c, props);
    if (!c)
        return null;
    return <SettingsContext.Provider value={context}><div className="react-settings-settings-user-font-dialog" style={{ display: 'contents' }}>
    <DialogTemplate>
    <Slot name="header">{"Custom fonts"}</Slot>
    <Dom as="div" slot={"content"} aria-busy={c.isLoading || !c.cacheLoaded} className={["font-manager min-w-0 space-y-4"].filter(Boolean).join(' ')}>
    <Dom as="p" className={["text-sm text-muted-foreground"].filter(Boolean).join(' ')}>{" Manage fonts stored in this browser. Choose a font to use it for this text style. "}</Dom>
    <Dom as="div" role={"group"} aria-label={"Custom font views"} className={["section-navigation"].filter(Boolean).join(' ')}>
        {['Stored', 'Add'].map((tab, index0) => <React.Fragment key={tab}><Button variant={"ghost"} shape={"rounded"} data-section-link={true} aria-pressed={c.currentTab === tab} disabled={c.isLoading || !c.fontCache} onClick={() => (c.controller.changed(c.currentTab = tab))} className={["min-h-11"].filter(Boolean).join(' ')}>{tab === 'Add' ? 'Add font' : 'Stored fonts'}</Button></React.Fragment>)}
    </Dom>
        {(c.error) ? <><Dom as="p" role={"alert"} className={["break-words text-sm text-destructive"].filter(Boolean).join(' ')}>{c.error}</Dom></> : null}
        {(!c.cacheLoaded) ? <><Dom as="p" role={"status"} className={["text-sm text-muted-foreground"].filter(Boolean).join(' ')}>{"Checking font storage…"}</Dom></> : <> {(!c.fontCache) ? <><Dom as="p" className={["text-sm text-muted-foreground"].filter(Boolean).join(' ')}>{"Your saved font list has not been changed."}</Dom>
            <Button variant={"outline"} onClick={c.loadCache}>{"Retry font storage"}</Button></> : <> {(c.currentTab === 'Stored') ? <>{(c.$userFonts$.length) ? <><Dom as="ul" aria-label={"Stored custom fonts"} className={["divide-y divide-border"].filter(Boolean).join(' ')}>
                        {(c.$userFonts$ ?? []).map((userFont, index1) => <React.Fragment key={userFont.path}><Dom as="li" className={["flex min-w-0 flex-wrap items-center gap-3 py-3"].filter(Boolean).join(' ')}>
                        <Dom as="div" className={["min-w-0 flex-1 basis-40"].filter(Boolean).join(' ')}>
                        <Dom as="p" className={["break-words font-medium"].filter(Boolean).join(' ')}>{userFont.name}</Dom>
                        <Dom as="p" className={["break-words text-xs text-muted-foreground"].filter(Boolean).join(' ')}>{userFont.fileName}</Dom>
                        {(!c.availablePaths.has(userFont.path)) ? <><Dom as="p" className={["mt-1 text-xs text-muted-foreground"].filter(Boolean).join(' ')}>{" File unavailable. Remove this entry, then add the file again. "}</Dom></> : null}
                        </Dom>
                        <Dom as="div" className={["flex flex-wrap gap-2"].filter(Boolean).join(' ')}>
                        <Button variant={"outline"} disabled={c.isLoading || !c.availablePaths.has(userFont.path)} aria-label={`Use ${userFont.name}`} onClick={() => c.selectFont(userFont)} className={["min-h-11"].filter(Boolean).join(' ')}>{"Use font"}</Button>
                        <Button variant={"destructive"} disabled={c.isLoading} aria-label={`Remove ${userFont.name}`} onClick={() => c.removeFont(userFont.path)} className={["min-h-11"].filter(Boolean).join(' ')}>{"Remove"}</Button>
                        </Dom>
                        </Dom></React.Fragment>)}
                    </Dom></> : <> <Dom as="p" className={["rounded-2xl bg-muted p-4 text-sm text-muted-foreground"].filter(Boolean).join(' ')}>{" No custom fonts yet. Add a font file to make it available here. "}</Dom></>}
                    {(c.isLoading) ? <><Dom as="p" role={"status"} className={["text-sm text-muted-foreground"].filter(Boolean).join(' ')}>{"Updating fonts…"}</Dom></> : null}</> : <> <SettingsUserFontAdd fontCache={c.fontCache} isLoading={c.isLoading} events={{ "saved": () => {
                            c.controller.changed(c.currentTab = 'Stored');
                            void c.loadCache();
                        } }} bindings={{ "isLoading": (value) => { c.controller.changed(c.isLoading = value); } }}></SettingsUserFontAdd></>}</>}</>}
    </Dom>
    <Slot name="footer"><Button variant={"ghost"} onClick={() => c.dispatch('close')} className={["min-h-11"].filter(Boolean).join(' ')}>{"Done"}</Button></Slot>
    </DialogTemplate>
    </div></SettingsContext.Provider>;
}
