// apps/web/src/lib/components/statistics/statistics-settings.svelte
<script lang="ts">
  import faLeftLong from '@lucide/svelte/icons/arrow-left';
  import faRightLong from '@lucide/svelte/icons/arrow-right';
  import { Button } from '$lib/components/ui/button';
  import CloseButton from '$lib/components/ui/close-button.svelte';
  import * as Sheet from '$lib/components/ui/sheet';
  import ButtonToggleGroup from '$lib/components/button-toggle-group/button-toggle-group.svelte';
  import { optionsForToggle } from '$lib/components/button-toggle-group/toggle-option';
  import SettingsItemGroup from '$lib/components/settings/settings-item-group.svelte';
  import {
    type StatisticsDateChange,
    statisticsRangeTemplates,
    readingTimeDataSources,
    charactersDataSources,
    readingSpeedDataSources,
    statisticsDataAggregrationModes,
    exportStatisticsData$,
    exportRawStatistics$,
    statisticsActionInProgress$,
    deleteStatisticsData$,
    setStatisticsDatesToAllTime$
  } from '$lib/components/statistics/statistics-types';
  import { daysOfWeek } from '$lib/components/statistics/statistics-heatmap/statistics-heatmap';
  import {
    confirmStatisticsDeletion$,
    lastCharactersDataSource$,
    lastPrimaryReadingDataAggregationMode$,
    lastReadingSpeedDataSource$,
    lastReadingTimeDataSource$,
    lastStartDayOfWeek$,
    lastStatisticsEndDate$,
    lastStatisticsRangeTemplate$,
    lastStatisticsStartDate$
  } from '$lib/data/store';
  import { createEventDispatcher } from 'svelte';
  import AppIcon from '$lib/components/app-icon.svelte';

  const dispatch = createEventDispatcher<{
    close: void;
    statisticsDateChange: StatisticsDateChange;
  }>();

  const weekDays = [...daysOfWeek.slice(1, 7), daysOfWeek[0]].map((day, index) => {
    if (day === 'Sunday') {
      return { day, index: 0 };
    }
    return { day, index: index + 1 };
  });

  $: selectedStatisticsStartDate = $lastStatisticsStartDate$;

  $: selectedStatisticsEndDate = $lastStatisticsEndDate$;

  async function exportStatisticsData(exportAllStatisticsData = true) {
    $statisticsActionInProgress$ = true;

    exportStatisticsData$.next(exportAllStatisticsData);
  }

  async function deleteStatisticsData(deleteAllStatisticsData = true) {
    $statisticsActionInProgress$ = true;

    deleteStatisticsData$.next(deleteAllStatisticsData);
  }
</script>

<div class="statistics-options">
  <div class="flex items-start justify-between gap-3">
    <Sheet.Title class="min-w-0 text-xl font-semibold">Statistics options</Sheet.Title>
    <CloseButton
      aria-label="Close statistics options"
      disabled={$statisticsActionInProgress$}
      onclick={() => dispatch('close')}
    />
  </div>
  <Sheet.Description>Choose your date range, measurements, and export format.</Sheet.Description>
  <fieldset disabled={$statisticsActionInProgress$} class="options-group">
    <legend>Date range</legend>
    <div class="fields">
      <div class="option-field">
        <label for="datesTemplate">Template</label>
        <select id="datesTemplate" bind:value={$lastStatisticsRangeTemplate$}>
          {#each statisticsRangeTemplates as template (template)}
            <option value={template}>{template}</option>
          {/each}
        </select>
      </div>
      <div class="option-field">
        <label for="weekDay">Start of Week</label>
        <select id="weekDay" bind:value={$lastStartDayOfWeek$}>
          {#each weekDays as weekDay (weekDay.day)}
            <option value={weekDay.index}>{weekDay.day}</option>
          {/each}
        </select>
      </div>
      <div class="option-field">
        <label for="fromDate">From</label>
        <input
          id="fromDate"
          type="date"
          value={selectedStatisticsStartDate}
          on:change={(event) =>
            dispatch('statisticsDateChange', {
              isStartDate: true,
              dateString: event.currentTarget.value
            })}
        />
      </div>
      <div class="option-field">
        <label for="toDate">To</label>
        <input
          id="toDate"
          type="date"
          value={selectedStatisticsEndDate}
          on:change={(event) =>
            dispatch('statisticsDateChange', {
              isStartDate: false,
              dateString: event.currentTarget.value
            })}
        />
      </div>
    </div>
    <div class="actions">
      <Button
        variant="ghost"
        aria-label="Set end date to start date"
        onclick={() => dispatch('statisticsDateChange', {
          isStartDate: false, dateString: selectedStatisticsStartDate
        })}
      ><AppIcon icon={faRightLong} />Use start date for both</Button>
      <Button
        variant="ghost"
        aria-label="Set start date to end date"
        onclick={() => dispatch('statisticsDateChange', {
          isStartDate: true, dateString: selectedStatisticsEndDate
        })}
      ><AppIcon icon={faLeftLong} />Use end date for both</Button>
      <Button
        variant="ghost"
        shape="rounded"
        onclick={() => setStatisticsDatesToAllTime$.next()}
        >Use all available dates for selected books</Button
      >
    </div>
  </fieldset>
  <fieldset disabled={$statisticsActionInProgress$} class="options-group">
    <legend>Measurements</legend>
    <p id="statistics-measurement-help" class="text-sm text-muted-foreground">
      Choose which values appear in the summary and how the reading data is grouped.
    </p>
    <div class="fields">
      <div class="option-field">
        <label for="timeDataSource">Time Data Source</label>
        <select id="timeDataSource" aria-describedby="statistics-measurement-help" bind:value={$lastReadingTimeDataSource$}>
          {#each readingTimeDataSources as source (source.key)}<option value={source.key}>{source.label}</option>{/each}
        </select>
      </div>
      <div class="option-field">
        <label for="charactersSource">Characters Data Source</label>
        <select id="charactersSource" aria-describedby="statistics-measurement-help" bind:value={$lastCharactersDataSource$}>
          {#each charactersDataSources as source (source.key)}<option value={source.key}>{source.label}</option>{/each}
        </select>
      </div>
      <div class="option-field">
        <label for="speedSource">Speed Data Source</label>
        <select id="speedSource" aria-describedby="statistics-measurement-help" bind:value={$lastReadingSpeedDataSource$}>
          {#each readingSpeedDataSources as source (source.key)}<option value={source.key}>{source.label}</option>{/each}
        </select>
      </div>
      <div class="option-field">
        <label for="primaryAggregration">Primary Aggregation</label>
        <select id="primaryAggregration" aria-describedby="statistics-measurement-help" bind:value={$lastPrimaryReadingDataAggregationMode$}>
          {#each statisticsDataAggregrationModes as mode (mode)}<option value={mode}>{mode}</option>{/each}
        </select>
      </div>
    </div>
  </fieldset>
  <fieldset disabled={$statisticsActionInProgress$} class="options-group">
    <legend>Export history</legend>
    <p class="text-sm text-muted-foreground">
      Raw history preserves book identities, unresolved legacy days, and migration receipts for
      recovery; it is not a TTU import file. The TTU ZIP exports use titles and cannot preserve
      book identities.
    </p>
    <div class="actions">
      <Button variant="secondary" onclick={() => {
        $statisticsActionInProgress$ = true;
        exportRawStatistics$.next();
      }}>Download raw history (JSON)</Button>
      <Button variant="outline" onclick={() => exportStatisticsData(false)}>Export Selection</Button>
      <Button variant="outline" onclick={() => exportStatisticsData()}>Export All</Button>
    </div>
  </fieldset>
  <fieldset disabled={$statisticsActionInProgress$} class="options-group">
    <legend>Manage history</legend>
    <SettingsItemGroup title="Confirm Statistics Deletion" applyHeaderClasses={false}>
      <ButtonToggleGroup
        invertColors
        options={optionsForToggle}
        bind:selectedOptionId={$confirmStatisticsDeletion$}
      />
    </SettingsItemGroup>
    <div class="actions">
      <Button variant="destructive" onclick={() => deleteStatisticsData(false)}>Delete Selection</Button>
      <Button variant="destructive" onclick={() => deleteStatisticsData()}>Delete All</Button>
    </div>
  </fieldset>
</div>

<style>
  .statistics-options {
    display: grid;
    flex-shrink: 0;
    min-width: 0;
    gap: 16px;
    padding: 20px;
    padding-bottom: max(20px, env(safe-area-inset-bottom));
  }
  .options-group {
    display: grid;
    min-width: 0;
    gap: 16px;
    margin-top: 8px;
    padding-top: 16px;
    border-top: 1px solid var(--border);
  }
  legend {
    padding-inline-end: 12px;
    font-weight: 600;
  }
  .fields {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(min(100%, 200px), 1fr));
    gap: 16px;
  }
  .option-field {
    display: grid;
    min-width: 0;
    gap: 6px;
  }
  label {
    font-size: 0.875rem;
  }
  input,
  select {
    width: 100%;
    min-width: 0;
    min-height: 44px;
    padding: 8px 10px;
    border: 1px solid var(--input);
    border-radius: 10px;
    background: var(--background);
    color: var(--foreground);
    font-size: 1rem;
  }
  input:focus-visible,
  select:focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 2px;
  }
  .actions {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
</style>

// apps/web/src/statistics-react/statistics-settings.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  AppIcon,
  Button,
  CloseButton,
  Sheet,
  useLatest,
  useReaderBindings,
  type ReaderViewProps,
  ReaderScope
} from './primitives';
import {
  createStatisticsSettings,
  type StatisticsSettingsProps
} from './statistics-settings-controller';
import { optionsForToggle } from '$lib/components/button-toggle-group/toggle-option';
import {
  statisticsRangeTemplates,
  readingTimeDataSources,
  charactersDataSources,
  readingSpeedDataSources,
  statisticsDataAggregrationModes,
  exportRawStatistics$,
  setStatisticsDatesToAllTime$
} from '$lib/components/statistics/statistics-types';

import { SettingsItemGroup } from '../settings-react/settings-item-group';
import { ButtonToggleGroup } from '../settings-react/button-toggle-group';

const faLeftLong = 'faLeftLong';
const faRightLong = 'faRightLong';
export function StatisticsSettings(props: Partial<StatisticsSettingsProps> & ReaderViewProps) {
  const latest = useLatest(props);
  const c = useReaderController(
    () =>
      createStatisticsSettings(props as StatisticsSettingsProps, (name, detail) =>
        latest.current.events?.[name]?.({ detail })
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <ReaderScope name="react-statistics-statistics-settings">
      <Dom as="div" className={['statistics-options'].filter(Boolean).join(' ')}>
        <Dom
          as="div"
          className={['flex flex-wrap-reverse items-start justify-between gap-3']
            .filter(Boolean)
            .join(' ')}
        >
          <Sheet.Title
            className={['min-w-min flex-auto break-normal text-xl font-semibold']
              .filter(Boolean)
              .join(' ')}
          >
            {'Statistics options'}
          </Sheet.Title>
          <CloseButton
            aria-label={'Close statistics options'}
            disabled={c.$statisticsActionInProgress$}
            onClick={() => c.dispatch('close')}
            className={['ms-auto'].filter(Boolean).join(' ')}
          ></CloseButton>
        </Dom>
        <Sheet.Description>
          {'Choose your date range, measurements, and export format.'}
        </Sheet.Description>
        <Dom
          as="fieldset"
          disabled={c.$statisticsActionInProgress$}
          className={['options-group'].filter(Boolean).join(' ')}
        >
          <Dom as="legend">{'Date range'}</Dom>
          <Dom as="div" className={['fields'].filter(Boolean).join(' ')}>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'datesTemplate'}>
                {'Template'}
              </Dom>
              <Dom
                as="select"
                id={'datesTemplate'}
                value={c.$lastStatisticsRangeTemplate$}
                bindings={{
                  value: (value) => {
                    c.$lastStatisticsRangeTemplate$ = value;
                  }
                }}
              >
                {(statisticsRangeTemplates ?? []).map((template, index0) => (
                  <React.Fragment key={template}>
                    <Dom as="option" value={template}>
                      {template}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'weekDay'}>
                {'Start of Week'}
              </Dom>
              <Dom
                as="select"
                id={'weekDay'}
                value={c.$lastStartDayOfWeek$}
                bindings={{
                  value: (value) => {
                    c.$lastStartDayOfWeek$ = value;
                  }
                }}
              >
                {(c.weekDays ?? []).map((weekDay, index1) => (
                  <React.Fragment key={weekDay.day}>
                    <Dom as="option" value={weekDay.index}>
                      {weekDay.day}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'fromDate'}>
                {'From'}
              </Dom>
              <Dom
                as="input"
                id={'fromDate'}
                type={'date'}
                value={c.selectedStatisticsStartDate}
                events={{
                  change: (event) =>
                    c.dispatch('statisticsDateChange', {
                      isStartDate: true,
                      dateString: event.currentTarget.value
                    })
                }}
              />
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'toDate'}>
                {'To'}
              </Dom>
              <Dom
                as="input"
                id={'toDate'}
                type={'date'}
                value={c.selectedStatisticsEndDate}
                events={{
                  change: (event) =>
                    c.dispatch('statisticsDateChange', {
                      isStartDate: false,
                      dateString: event.currentTarget.value
                    })
                }}
              />
            </Dom>
          </Dom>
          <Dom as="div" className={['actions'].filter(Boolean).join(' ')}>
            <Button
              variant={'ghost'}
              aria-label={'Set end date to start date'}
              onClick={() =>
                c.dispatch('statisticsDateChange', {
                  isStartDate: false,
                  dateString: c.selectedStatisticsStartDate
                })
              }
            >
              <AppIcon icon={faRightLong}></AppIcon>
              {'Use start date for both'}
            </Button>
            <Button
              variant={'ghost'}
              aria-label={'Set start date to end date'}
              onClick={() =>
                c.dispatch('statisticsDateChange', {
                  isStartDate: true,
                  dateString: c.selectedStatisticsEndDate
                })
              }
            >
              <AppIcon icon={faLeftLong}></AppIcon>
              {'Use end date for both'}
            </Button>
            <Button
              variant={'ghost'}
              shape={'rounded'}
              onClick={() => setStatisticsDatesToAllTime$.next()}
            >
              {'Use all available dates for selected books'}
            </Button>
          </Dom>
        </Dom>
        <Dom
          as="fieldset"
          disabled={c.$statisticsActionInProgress$}
          className={['options-group'].filter(Boolean).join(' ')}
        >
          <Dom as="legend">{'Measurements'}</Dom>
          <Dom
            as="p"
            id={'statistics-measurement-help'}
            className={['text-sm text-muted-foreground'].filter(Boolean).join(' ')}
          >
            {' Choose which values appear in the summary and how the reading data is grouped. '}
          </Dom>
          <Dom as="div" className={['fields'].filter(Boolean).join(' ')}>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'timeDataSource'}>
                {'Time Data Source'}
              </Dom>
              <Dom
                as="select"
                id={'timeDataSource'}
                aria-describedby={'statistics-measurement-help'}
                value={c.$lastReadingTimeDataSource$}
                bindings={{
                  value: (value) => {
                    c.$lastReadingTimeDataSource$ = value;
                  }
                }}
              >
                {(readingTimeDataSources ?? []).map((source, index2) => (
                  <React.Fragment key={source.key}>
                    <Dom as="option" value={source.key}>
                      {source.label}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'charactersSource'}>
                {'Characters Data Source'}
              </Dom>
              <Dom
                as="select"
                id={'charactersSource'}
                aria-describedby={'statistics-measurement-help'}
                value={c.$lastCharactersDataSource$}
                bindings={{
                  value: (value) => {
                    c.$lastCharactersDataSource$ = value;
                  }
                }}
              >
                {(charactersDataSources ?? []).map((source, index3) => (
                  <React.Fragment key={source.key}>
                    <Dom as="option" value={source.key}>
                      {source.label}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'speedSource'}>
                {'Speed Data Source'}
              </Dom>
              <Dom
                as="select"
                id={'speedSource'}
                aria-describedby={'statistics-measurement-help'}
                value={c.$lastReadingSpeedDataSource$}
                bindings={{
                  value: (value) => {
                    c.$lastReadingSpeedDataSource$ = value;
                  }
                }}
              >
                {(readingSpeedDataSources ?? []).map((source, index4) => (
                  <React.Fragment key={source.key}>
                    <Dom as="option" value={source.key}>
                      {source.label}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
            <Dom as="div" className={['option-field'].filter(Boolean).join(' ')}>
              <Dom as="label" htmlFor={'primaryAggregration'}>
                {'Primary Aggregation'}
              </Dom>
              <Dom
                as="select"
                id={'primaryAggregration'}
                aria-describedby={'statistics-measurement-help'}
                value={c.$lastPrimaryReadingDataAggregationMode$}
                bindings={{
                  value: (value) => {
                    c.$lastPrimaryReadingDataAggregationMode$ = value;
                  }
                }}
              >
                {(statisticsDataAggregrationModes ?? []).map((mode, index5) => (
                  <React.Fragment key={mode}>
                    <Dom as="option" value={mode}>
                      {mode}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Dom>
          </Dom>
        </Dom>
        <Dom
          as="fieldset"
          disabled={c.$statisticsActionInProgress$}
          className={['options-group'].filter(Boolean).join(' ')}
        >
          <Dom as="legend">{'Export history'}</Dom>
          <Dom as="p" className={['text-sm text-muted-foreground'].filter(Boolean).join(' ')}>
            {
              ' Raw history preserves book identities, unresolved legacy days, and migration receipts for recovery; it is not a TTU import file. The TTU ZIP exports use titles and cannot preserve book identities. '
            }
          </Dom>
          <Dom as="div" className={['actions'].filter(Boolean).join(' ')}>
            <Button
              variant={'secondary'}
              onClick={() => {
                c.$statisticsActionInProgress$ = true;
                exportRawStatistics$.next();
              }}
            >
              {'Download raw history (JSON)'}
            </Button>
            <Button variant={'outline'} onClick={() => c.exportStatisticsData(false)}>
              {'Export Selection'}
            </Button>
            <Button variant={'outline'} onClick={() => c.exportStatisticsData()}>
              {'Export All'}
            </Button>
          </Dom>
        </Dom>
        <Dom
          as="fieldset"
          disabled={c.$statisticsActionInProgress$}
          className={['options-group'].filter(Boolean).join(' ')}
        >
          <Dom as="legend">{'Manage history'}</Dom>
          <SettingsItemGroup title={'Confirm Statistics Deletion'} applyHeaderClasses={false}>
            <ButtonToggleGroup
              invertColors={true}
              options={optionsForToggle}
              selectedOptionId={c.$confirmStatisticsDeletion$}
              bindings={{
                selectedOptionId: (value) => {
                  c.$confirmStatisticsDeletion$ = value;
                }
              }}
            ></ButtonToggleGroup>
          </SettingsItemGroup>
          <Dom as="div" className={['actions'].filter(Boolean).join(' ')}>
            <Button variant={'destructive'} onClick={() => c.deleteStatisticsData(false)}>
              {'Delete Selection'}
            </Button>
            <Button variant={'destructive'} onClick={() => c.deleteStatisticsData()}>
              {'Delete All'}
            </Button>
          </Dom>
        </Dom>
      </Dom>
    </ReaderScope>
  );
}
