// apps/web/src/settings-react/button-toggle-group.tsx
/**
 * @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors
 * All rights reserved.
 */

import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  Button,
  Switch,
  useLatest,
  useReaderBindings,
  slotContent,
  type ReaderViewProps
} from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import {
  createButtonToggleGroup,
  type ButtonToggleGroupProps
} from './button-toggle-group-controller';

import { availableThemes } from '$lib/data/theme-option';
export function ButtonToggleGroup(
  props: Partial<ButtonToggleGroupProps> &
    ReaderViewProps & {
      children?: React.ReactNode;
      onClose?: () => void;
      slot?: string;
    }
) {
  const latest = useLatest(props);
  const context = useSettingsContext();
  const c = useReaderController(
    () =>
      createButtonToggleGroup(
        props as ButtonToggleGroupProps,
        (name, detail) => {
          latest.current.events?.[name]?.({ detail });
          if (name === 'close') latest.current.onClose?.();
        },
        context
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <SettingsContext.Provider value={context}>
      <div className="react-settings-button-toggle-group" style={{ display: 'contents' }}>
        {c.isBoolean ? (
          <>
            <Dom as="div" className={['flex min-h-9 items-center gap-3'].filter(Boolean).join(' ')}>
              <Switch
                aria-label={c.fieldName()}
                checked={c.selectedOptionId === true}
                onCheckedChange={(value) => c.controller.changed((c.selectedOptionId = value))}
              ></Switch>
              <Dom
                as="span"
                className={['text-sm text-muted-foreground'].filter(Boolean).join(' ')}
              >
                {c.selectedOptionId ? 'On' : 'Off'}
              </Dom>
            </Dom>
          </>
        ) : (
          <>
            {' '}
            <Dom
              as="div"
              role={'group'}
              aria-label={c.fieldName()}
              className={['flex flex-wrap gap-2', c.invertColors && 'legacy-invert']
                .filter(Boolean)
                .join(' ')}
            >
              {(c.options ?? []).map((option, _index0) => (
                <React.Fragment key={option.id}>
                  <Dom
                    as="div"
                    className={['flex flex-wrap items-center gap-1'].filter(Boolean).join(' ')}
                  >
                    <Button
                      title={String(option.id)}
                      variant={option.id === c.selectedOptionId ? 'secondary' : 'outline'}
                      aria-pressed={option.id === c.selectedOptionId}
                      styleText={c.styles(option.style)}
                      onClick={() => c.controller.changed((c.selectedOptionId = option.id))}
                      className={[
                        option.id === c.selectedOptionId
                          ? 'border-2 border-primary'
                          : 'border-border'
                      ]
                        .filter(Boolean)
                        .join(' ')}
                    >
                      {option.text}
                    </Button>
                    {option.showIcons &&
                    option.id === c.selectedOptionId &&
                    !availableThemes.has(option.id) ? (
                      <>
                        <Button
                          variant={'ghost'}
                          aria-label={`Edit ${option.text} theme`}
                          onClick={() => c.dispatch('edit', option.id)}
                        >
                          {'Edit'}
                        </Button>
                        <Button
                          variant={'ghost'}
                          aria-label={`Delete ${option.text} theme`}
                          onClick={() => c.dispatch('delete', option.id)}
                        >
                          {'Delete'}
                        </Button>
                      </>
                    ) : null}
                  </Dom>
                </React.Fragment>
              ))}
              {slotContent(props.children, undefined)}
            </Dom>
          </>
        )}
      </div>
    </SettingsContext.Provider>
  );
}

// apps/web/src/lib/components/button-toggle-group/button-toggle-group.svelte
<script lang="ts">
  import { createEventDispatcher, getContext } from 'svelte';
  import { Button } from '$lib/components/ui/button';
  import { Switch } from '$lib/components/ui/switch';
  import { SETTINGS_FIELD } from '$lib/components/settings/settings-context';
  import type { ToggleOption } from './toggle-option';
  import { availableThemes } from '$lib/data/theme-option';
  export let options: ToggleOption<any>[];
  export let selectedOptionId: any;
  export let invertColors = false;
  const fieldName = getContext<() => string>(SETTINGS_FIELD) ?? (() => 'Option');
  const dispatch = createEventDispatcher<{ edit: string; delete: string }>();
  $: isBoolean =
    options.length === 2 &&
    options.some((o) => o.id === true) &&
    options.some((o) => o.id === false);
  function styles(style: Record<string, any> | undefined) {
    return style
      ? Object.entries(style)
          .map(([key, value]) => `${key}: ${value}`)
          .join(';')
      : '';
  }
</script>

{#if isBoolean}
  <div class="flex min-h-9 items-center gap-3">
    <Switch
      aria-label={fieldName()}
      checked={selectedOptionId === true}
      onCheckedChange={(value) => (selectedOptionId = value)}
    />
    <span class="text-sm text-muted-foreground">{selectedOptionId ? 'On' : 'Off'}</span>
  </div>
{:else}
  <div
    role="group"
    aria-label={fieldName()}
    class="flex flex-wrap gap-2"
    class:legacy-invert={invertColors}
  >
    {#each options as option (option.id)}
      <div class="flex flex-wrap items-center gap-1">
        <Button
          title={String(option.id)}
          variant={option.id === selectedOptionId ? 'secondary' : 'outline'}
          class={option.id === selectedOptionId ? 'border-2 border-primary' : 'border-border'}
          aria-pressed={option.id === selectedOptionId}
          style={styles(option.style)}
          onclick={() => (selectedOptionId = option.id)}>{option.text}</Button
        >
        {#if option.showIcons && option.id === selectedOptionId && !availableThemes.has(option.id)}
          <Button
            variant="ghost"
            aria-label={`Edit ${option.text} theme`}
            onclick={() => dispatch('edit', option.id)}>Edit</Button
          >
          <Button
            variant="ghost"
            aria-label={`Delete ${option.text} theme`}
            onclick={() => dispatch('delete', option.id)}>Delete</Button
          >
        {/if}
      </div>
    {/each}
    <slot />
  </div>
{/if}
