// apps/web/src/settings-react/settings-item-group.tsx
/**
 * @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors
 * All rights reserved.
 */

import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  Field,
  useLatest,
  useReaderBindings,
  slotContent,
  type ReaderViewProps
} from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import {
  createSettingsItemGroup,
  type SettingsItemGroupProps
} from './settings-item-group-controller';

export function SettingsItemGroup(
  props: Partial<SettingsItemGroupProps> &
    ReaderViewProps & {
      children?: React.ReactNode;
      onClose?: () => void;
      slot?: string;
    }
) {
  const latest = useLatest(props);
  const context = useSettingsContext();
  const c = useReaderController(
    () =>
      createSettingsItemGroup(
        props as SettingsItemGroupProps,
        (name, detail) => {
          latest.current.events?.[name]?.({ detail });
          if (name === 'close') latest.current.onClose?.();
        },
        context
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <SettingsContext.Provider value={context}>
      <div className="react-settings-settings-item-group" style={{ display: 'contents' }}>
        <Dom
          as="section"
          data-setting={c.settingId || c.title}
          data-category={c.category}
          hidden={!c.visible}
          aria-labelledby={c.showHeading ? c.headingId : undefined}
          className={[
            [
              'appearance',
              'selected-theme',
              'storage-sources',
              'reading-goals',
              'font-defaults'
            ].includes(c.settingId) && 'wide',
            'settings-field rounded-2xl bg-card p-[16px] text-card-foreground ring-1 ring-border/60 sm:p-[20px]'
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <Field.Field>
            {c.showHeading ? (
              <>
                <Dom
                  as="div"
                  className={['flex flex-wrap items-center justify-between gap-2']
                    .filter(Boolean)
                    .join(' ')}
                >
                  <Dom
                    as="h2"
                    id={c.headingId}
                    className={['text-sm', c.applyHeaderClasses && 'font-semibold']
                      .filter(Boolean)
                      .join(' ')}
                  >
                    {c.title}
                  </Dom>
                  {slotContent(props.children, 'header')}
                </Dom>
              </>
            ) : null}
            {c.tooltip ? (
              <>
                <Field.Description className={['whitespace-pre-line'].filter(Boolean).join(' ')}>
                  {c.tooltip}
                </Field.Description>
              </>
            ) : null}
            <Dom as="div" className={['min-w-0'].filter(Boolean).join(' ')}>
              {slotContent(props.children, undefined)}
            </Dom>
          </Field.Field>
        </Dom>
      </div>
    </SettingsContext.Provider>
  );
}

// apps/web/src/lib/components/settings/settings-item-group.svelte
<script lang="ts">
  import { getContext, setContext } from 'svelte';
  import { readable } from 'svelte/store';
  import * as Field from '$lib/components/ui/field';
  import {
    SETTINGS_FILTER,
    SETTINGS_FIELD,
    matchesSetting,
    type SettingsFilterStore
  } from './settings-context';
  export let title: string;
  export let tooltip = '';
  export let applyHeaderClasses = true;
  export let category = 'all';
  export let settingId = '';
  export let keywords = '';
  export let showHeading = true;
  const filter =
    getContext<SettingsFilterStore>(SETTINGS_FILTER) ?? readable({ category: 'all', query: '' });
  setContext(SETTINGS_FIELD, () => title);
  $: visible = matchesSetting($filter, category, `${title} ${tooltip} ${keywords}`);
  $: headingId = settingId ? `setting-${settingId}-heading` : undefined;
</script>

<section
  data-setting={settingId || title}
  data-category={category}
  hidden={!visible}
  class:wide={[
    'appearance',
    'selected-theme',
    'storage-sources',
    'reading-goals',
    'font-defaults'
  ].includes(settingId)}
  class="settings-field rounded-2xl bg-card p-4 text-card-foreground ring-1 ring-border/60 sm:p-5"
  aria-labelledby={showHeading ? headingId : undefined}
>
  <Field.Field>
    {#if showHeading}
      <div class="flex flex-wrap items-center justify-between gap-2">
        <h2 id={headingId} class="text-sm" class:font-semibold={applyHeaderClasses}>{title}</h2>
        <slot name="header" />
      </div>
    {/if}
    {#if tooltip}<Field.Description class="whitespace-pre-line">{tooltip}</Field.Description>{/if}
    <div class="min-w-0"><slot /></div>
  </Field.Field>
</section>

<style>
  .settings-field[hidden] {
    display: none;
  }
  .settings-field {
    min-width: 0;
  }
  .wide {
    grid-column: 1 / -1;
  }
</style>
