// apps/web/src/settings-react/settings-header.tsx
/**
 * @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors
 * All rights reserved.
 */

import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  Icon,
  Button,
  AppNav,
  useLatest,
  useReaderBindings,
  type ReaderViewProps
} from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import { createSettingsHeader, type SettingsHeaderProps } from './settings-header-controller';
export function SettingsHeader(
  props: Partial<SettingsHeaderProps> &
    ReaderViewProps & {
      children?: React.ReactNode;
      onClose?: () => void;
      slot?: string;
    }
) {
  const latest = useLatest(props);
  const context = useSettingsContext();
  const c = useReaderController(
    () =>
      createSettingsHeader(
        props as SettingsHeaderProps,
        (name, detail) => {
          latest.current.events?.[name]?.({ detail });
          if (name === 'close') latest.current.onClose?.();
        },
        context
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <SettingsContext.Provider value={context}>
      <div className="react-settings-settings-header" style={{ display: 'contents' }}>
        <Dom
          as="header"
          className={['app-header settings-header border-b border-border bg-card text-foreground']
            .filter(Boolean)
            .join(' ')}
        >
          <Button
            href={c.leavePageLink}
            variant={'ghost'}
            aria-label={'Back'}
            className={['settings-back'].filter(Boolean).join(' ')}
          >
            <Icon
              name="CaretLeftIcon"
              aria-hidden={'true'}
              className={['size-5 shrink-0'].filter(Boolean).join(' ')}
            ></Icon>
            <Dom as="span" className={['back-label'].filter(Boolean).join(' ')}>
              {'Back'}
            </Dom>
          </Button>
          <Dom as="h1" className={['settings-title font-semibold'].filter(Boolean).join(' ')}>
            {'Settings'}
          </Dom>
          <Dom as="div" className={['settings-navigation'].filter(Boolean).join(' ')}>
            <AppNav compact></AppNav>
          </Dom>
        </Dom>
      </div>
    </SettingsContext.Provider>
  );
}

// apps/web/src/lib/components/settings/settings-header.svelte
<script lang="ts">
  import AppNav from '$lib/components/navigation/app-nav.svelte';
  import { Button } from '$lib/components/ui/button';
  import { CaretLeftIcon } from 'phosphor-svelte';
  export let leavePageLink: string;
</script>

<header class="app-header settings-header border-b border-border bg-card text-foreground">
  <Button href={leavePageLink} variant="ghost" aria-label="Back" class="settings-back">
    <CaretLeftIcon class="size-5 shrink-0" aria-hidden="true" />
    <span class="back-label">Back</span>
  </Button>
  <span class="settings-title font-semibold">Settings</span>
  <div class="settings-navigation"><AppNav compact /></div>
</header>

<style>
  .settings-header {
    display: grid;
    grid-template-columns: 44px minmax(0, 1fr) 44px;
    align-items: center;
    gap: 8px;
    min-height: 64px;
    padding: 8px 12px;
  }
  .settings-title {
    min-width: 0;
    overflow-wrap: anywhere;
  }
  .settings-navigation {
    min-width: 0;
    justify-self: end;
  }
  .back-label {
    display: none;
  }
  .settings-header :global(.settings-back) {
    width: 44px;
    height: 44px;
    min-height: 44px;
    padding: 0;
    border-radius: 50%;
  }
  @media (min-width: 640px) {
    .settings-header {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
      padding-inline: 24px;
    }
    .settings-navigation {
      margin-inline-start: auto;
    }
    .back-label {
      display: inline;
    }
    .settings-header :global(.settings-back) {
      width: auto;
      height: auto;
      padding: 8px 12px;
      border-radius: 12px;
    }
  }
</style>
