// apps/web/src/settings-react/settings-workspace.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController, readerTick } from '../reader-react/controller';
import { Dom, SurfaceEvents, Head, Icon, AppIcon, Button, Input, Switch, Field, Popover, DialogTemplate, ActionMenu, AppNav, Menu, useLatest, useReaderBindings, slotContent, Slot, type ReaderViewProps } from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import { createSettingsWorkspace, type SettingsWorkspaceProps } from './settings-workspace-controller';
import { afterNavigate, goto } from '$app/navigation';
import { resolve } from '$app/paths';
import { SETTINGS_FILTER } from '../lib/components/settings/settings-context';
import { SettingsOfflineStatus } from './settings-offline-status';
import { SettingsItemGroup } from './settings-item-group';
import { PageTurnEffectSelect } from './page-turn-effect-select';
export function SettingsWorkspace(props: Partial<SettingsWorkspaceProps> & ReaderViewProps & {
    children?: React.ReactNode;
    onClose?: () => void;
    slot?: string;
}) {
    const latest = useLatest(props);
    const context = useSettingsContext();
    const c = useReaderController(() => createSettingsWorkspace(props as SettingsWorkspaceProps, (name, detail) => { latest.current.events?.[name]?.({ detail }); if (name === 'close')
        latest.current.onClose?.(); }, context), props);
    useReaderBindings(c, props);
    if (!c)
        return null;
    return <SettingsContext.Provider value={context}><div className="react-settings-settings-workspace" style={{ display: 'contents' }}>
    <Dom as="div" elementRef={(value: typeof c.root) => { c.controller.changed(c.root = value); }} className={["settings-workspace grid min-w-0 grid-cols-1 gap-6 lg:grid-cols-[14rem_minmax(0,1fr)]"].filter(Boolean).join(' ')}>
    <Dom as="aside" aria-label={"Settings sections"} className={["min-w-0 self-start lg:sticky lg:top-20"].filter(Boolean).join(' ')}>
    <Dom as="label" htmlFor={"settings-search"} className={["mb-2 block text-sm font-medium"].filter(Boolean).join(' ')}>{"Search settings"}</Dom>
    <Input id={"settings-search"} aria-describedby={c.$filter.query ? 'settings-search-results' : undefined} type={"search"} placeholder={"Search all settings…"} value={c.$filter.query} onInput={(event: React.FormEvent<HTMLInputElement>) => c.filter.update((value) => ({ ...value, query: event.currentTarget.value }))}></Input>
    <Dom as="nav" aria-label={"Settings categories"} className={["section-navigation section-navigation-sidebar mt-3"].filter(Boolean).join(' ')}>
        {(c.categories ?? []).map((category, index0) => <React.Fragment key={category.id}><Button href={`#${category.id}`} variant={"ghost"} shape={"rounded"} data-section-link={true} aria-current={c.$filter.category === category.id && !c.$filter.query ? 'page' : undefined} onClick={(event: MouseEvent & { currentTarget: HTMLAnchorElement }) => c.handleCategoryClick(event, category.id)} className={["justify-start"].filter(Boolean).join(' ')}>{category.label}</Button></React.Fragment>)}
    </Dom>
    </Dom>
    <Dom as="main" id={"settings-content"} className={["min-w-0"].filter(Boolean).join(' ')}>
    <Dom as="div" className={["mb-5"].filter(Boolean).join(' ')}>
    <Dom as="h1" className={["text-2xl font-semibold tracking-tight"].filter(Boolean).join(' ')}>
    {c.$filter.query ? 'Search results' : c.selected.label}
    </Dom>
    <Dom as="p" className={["mt-1 text-sm text-muted-foreground"].filter(Boolean).join(' ')}>
    {c.$filter.query ? 'Results across every settings section.' : c.selected.description}
    </Dom>
    <Dom as="p" className={["mt-2 text-xs text-muted-foreground"].filter(Boolean).join(' ')}>{" Changes save automatically. Reading goals have separate Save and Cancel actions. "}</Dom>
        {(c.$filter.query) ? <><Dom as="p" id={"settings-search-results"} role={"status"} aria-label={"Settings search results"} className={["mt-3 text-sm"].filter(Boolean).join(' ')}>
            {c.visibleCount ? `${c.visibleCount} matching settings`
                : 'No matching settings. Try a different search.'}
        </Dom></> : null}
    </Dom>
    <SettingsOfflineStatus></SettingsOfflineStatus>
    <SettingsItemGroup settingId={"page-turn-effect"} category={"layout"} keywords={"pageTurnEffect slide none animation pagination"} title={"Page turn effect"} showHeading={false}>
    <PageTurnEffectSelect></PageTurnEffectSelect>
    </SettingsItemGroup>
    {slotContent(props.children, undefined)}
    </Dom>
    </Dom>
    </div></SettingsContext.Provider>;
}

// apps/web/src/lib/components/settings/settings-workspace.svelte
<script lang="ts">
  import { setContext, onMount, tick } from 'svelte';
  import { afterNavigate, goto } from '$app/navigation';
  import { resolve } from '$app/paths';
  import { writable } from 'svelte/store';
  import { Input } from '$lib/components/ui/input';
  import { Button } from '$lib/components/ui/button';
  import { SETTINGS_FILTER } from './settings-context';
  import PageTurnEffectSelect from './page-turn-effect-select.svelte';
  import SettingsItemGroup from './settings-item-group.svelte';
  import SettingsOfflineStatus from './settings-offline-status.svelte';
  const categories = [
    {
      id: 'appearance',
      label: 'Appearance',
      description: 'Theme, light and dark mode, and background images'
    },
    {
      id: 'typography',
      label: 'Fonts & text',
      description: 'Typography, spacing, and Japanese font options'
    },
    {
      id: 'layout',
      label: 'Page layout',
      description: 'Writing direction, pagination, and margins'
    },
    {
      id: 'reading',
      label: 'Reading controls',
      description: 'Bookmarks, navigation, furigana, and images'
    },
    {
      id: 'library',
      label: 'Library & sync',
      description: 'Storage sources, import, export, and backups'
    },
    {
      id: 'tracking',
      label: 'Tracking & goals',
      description: 'Reading statistics, session behavior, and goals'
    },
    {
      id: 'all',
      label: 'All settings',
      description: 'Every available setting, grouped in one place'
    }
  ];
  const filter = writable({ category: 'appearance', query: '' });
  setContext(SETTINGS_FILTER, filter);
  let root: HTMLElement;
  let visibleCount = 0;
  $: selected = categories.find((category) => category.id === $filter.category) ?? categories[0];
  afterNavigate(({ to }) => {
    const category = to?.url.hash.slice(1);
    filter.set({
      category:
        category && categories.some((item) => item.id === category) ? category : 'appearance',
      query: ''
    });
  });
  onMount(() => {
    const countVisibleSettings = () => {
      if (root?.isConnected)
        visibleCount = root.querySelectorAll('[data-setting]:not([hidden])').length;
    };
    const stop = filter.subscribe(() => {
      void tick().then(countVisibleSettings);
    });
    // Enabling tracking or changing writing mode mounts conditional fields even
    // when the search hasn't changed. Count those real fields, not stale results.
    const observer = new MutationObserver(countVisibleSettings);
    observer.observe(root, {
      subtree: true,
      childList: true,
      attributes: true,
      attributeFilter: ['hidden']
    });
    countVisibleSettings();
    return () => {
      stop();
      observer.disconnect();
    };
  });
  function choose(category: string) {
    filter.set({ category, query: '' });
    if (typeof window === 'undefined' || window.location.hash === `#${category}`) return;
    void goto(resolve(`/settings#${category}`), {
      keepFocus: true,
      noScroll: true
    });
  }
  function handleCategoryClick(event: MouseEvent, category: string) {
    if (event.button !== 0 || event.altKey || event.ctrlKey || event.metaKey || event.shiftKey)
      return;
    event.preventDefault();
    choose(category);
  }
</script>

<div
  class="settings-workspace grid min-w-0 grid-cols-1 gap-6 lg:grid-cols-[14rem_minmax(0,1fr)]"
  bind:this={root}
>
  <aside class="min-w-0 self-start lg:sticky lg:top-20" aria-label="Settings sections">
    <label for="settings-search" class="mb-2 block text-sm font-medium">Search settings</label>
    <Input
      id="settings-search"
      aria-describedby={$filter.query ? 'settings-search-results' : undefined}
      type="search"
      placeholder="Search all settings…"
      value={$filter.query}
      oninput={(event) =>
        filter.update((value) => ({ ...value, query: event.currentTarget.value }))}
    />
    <nav
      aria-label="Settings categories"
      class="section-navigation section-navigation-sidebar mt-3"
    >
      {#each categories as category (category.id)}
        <Button
          href={`#${category.id}`}
          variant="ghost"
          shape="rounded"
          data-section-link
          class="justify-start"
          aria-current={$filter.category === category.id && !$filter.query ? 'page' : undefined}
          onclick={(event) => handleCategoryClick(event, category.id)}>{category.label}</Button
        >
      {/each}
    </nav>
  </aside>
  <main class="min-w-0" id="settings-content">
    <div class="mb-5">
      <h1 class="text-2xl font-semibold tracking-tight">
        {$filter.query ? 'Search results' : selected.label}
      </h1>
      <p class="mt-1 text-sm text-muted-foreground">
        {$filter.query ? 'Results across every settings section.' : selected.description}
      </p>
      <p class="mt-2 text-xs text-muted-foreground">
        Changes save automatically. Reading goals have separate Save and Cancel actions.
      </p>
      {#if $filter.query}<p
          id="settings-search-results"
          role="status"
          aria-label="Settings search results"
          class="mt-3 text-sm"
        >
          {visibleCount
            ? `${visibleCount} matching settings`
            : 'No matching settings. Try a different search.'}
        </p>{/if}
    </div>
    <SettingsOfflineStatus />
    <SettingsItemGroup
      settingId="page-turn-effect"
      category="layout"
      keywords="pageTurnEffect slide none animation pagination"
      title="Page turn effect"
      showHeading={false}
    >
      <PageTurnEffectSelect />
    </SettingsItemGroup>
    <slot />
  </main>
</div>

<style>
  :global([data-setting='page-turn-effect']:not([hidden])),
  :global([data-setting='offline-reading']:not([hidden])) {
    margin-bottom: 1.25rem;
  }
</style>
