// apps/web/src/statistics-react/statistics-summary-header.tsx
/** @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors. All rights reserved. */
import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  AppIcon,
  useLatest,
  useReaderBindings,
  type ReaderViewProps,
  Popover,
  ReaderScope
} from './primitives';
import {
  createStatisticsSummaryHeader,
  type StatisticsSummaryHeaderProps
} from './statistics-summary-header-controller';

import { SortDirection } from '$lib/data/sort-types';

const faArrowDownWideShort = 'faArrowDownWideShort';
const faArrowUpShortWide = 'faArrowUpShortWide';
export function StatisticsSummaryHeader(
  props: Partial<StatisticsSummaryHeaderProps> & ReaderViewProps
) {
  const latest = useLatest(props);
  const c = useReaderController(
    () =>
      createStatisticsSummaryHeader(props as StatisticsSummaryHeaderProps, (name, detail) =>
        latest.current.events?.[name]?.({ detail })
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <ReaderScope name="react-statistics-statistics-summary-header">
      <Dom
        as="div"
        className={[c.tableHeaderClasses, c.isHidden && 'hidden'].filter(Boolean).join(' ')}
        style={{ gridRow: c.gridRow ? `${c.gridRow}/${c.gridRow}` : null }}
      >
        {c.options.length > 1 && !c.hasRowInEdit ? (
          <>
            <Popover
              placement={'bottom-start'}
              fallbackPlacements={['top']}
              innerContainerStyles={'width: 100%'}
              containerStyles={'flex: 1;'}
              bindings={{
                this: (value) => {
                  c.summaryHeaderPopover = value;
                }
              }}
            >
              <Dom as="div" title={c.title}>
                {c.selectedOption.label}
              </Dom>
              <Dom
                as="div"
                slot={'content'}
                className={['flex flex-col overflow-auto w-46 p-2'].filter(Boolean).join(' ')}
              >
                {(c.options ?? []).map((option, index0) => (
                  <React.Fragment key={option.key}>
                    <Dom
                      as="button"
                      className={[
                        'flex flex-1 my-2 hover:opacity-50 hover:bg-accent hover:text-foreground'
                      ]
                        .filter(Boolean)
                        .join(' ')}
                      events={{
                        click: (event) => {
                          event.stopPropagation();
                          Reflect.apply(
                            () => {
                              c.selectedOption = option;
                              c.dispatch('propertyChange', {
                                property: option.key,
                                statisticsSummaryKey: c.statisticsSummaryKey
                              });
                              c.summaryHeaderPopover.toggleOpen();
                            },
                            undefined,
                            [event]
                          );
                        }
                      }}
                    >
                      {option.label}
                    </Dom>
                  </React.Fragment>
                ))}
              </Dom>
            </Popover>
          </>
        ) : (
          <>
            {' '}
            <Dom
              as="button"
              disabled={c.hasRowInEdit}
              title={c.title}
              className={['flex flex-1 text-left', c.hasRowInEdit && 'cursor-not-allowed']
                .filter(Boolean)
                .join(' ')}
              events={{
                click: () => {
                  c.dispatch('propertyChange', {
                    property: c.selectedOption.key,
                    statisticsSummaryKey: c.statisticsSummaryKey
                  });
                }
              }}
            >
              {c.selectedOption.label}
            </Dom>
          </>
        )}
        <Dom
          as="button"
          title={'Click to select/sort by this Attribute'}
          aria-label={`Sort by ${c.selectedOption.label}`}
          disabled={c.hasRowInEdit}
          className={[
            'ml-4',
            !c.optionKeys.has(c.$lastStatisticsSummarySortProperty$) && 'opacity-20',
            c.hasRowInEdit && 'cursor-not-allowed'
          ]
            .filter(Boolean)
            .join(' ')}
          events={{
            click: () =>
              c.dispatch('propertyChange', {
                property: c.selectedOption.key,
                statisticsSummaryKey: c.statisticsSummaryKey
              })
          }}
        >
          {c.$lastStatisticsSummarySortDirection$ === SortDirection.ASC ? (
            <>
              <AppIcon icon={faArrowUpShortWide}></AppIcon>
            </>
          ) : (
            <>
              {' '}
              <AppIcon icon={faArrowDownWideShort}></AppIcon>
            </>
          )}
        </Dom>
      </Dom>
    </ReaderScope>
  );
}

// apps/web/src/lib/components/statistics/statistics-summary/statistics-summary-header.svelte
<script lang="ts">
  import faArrowDownWideShort from '@lucide/svelte/icons/arrow-down-wide-narrow';
  import faArrowUpShortWide from '@lucide/svelte/icons/arrow-up-narrow-wide';
  import Popover from '$lib/components/popover/popover.svelte';
  import type {
    StatisticsDataSourceChange,
    StatisticsSummaryKey
  } from '$lib/components/statistics/statistics-summary/statistics-summary';
  import type {
    BookStatistic,
    StatisticsDataSource
  } from '$lib/components/statistics/statistics-types';
  import { SortDirection } from '$lib/data/sort-types';
  import {
    lastStatisticsSummarySortDirection$,
    lastStatisticsSummarySortProperty$
  } from '$lib/data/store';
  import { createEventDispatcher } from 'svelte';
  import AppIcon from '$lib/components/app-icon.svelte';

  export let statisticsSummaryKey: StatisticsSummaryKey;
  export let options: StatisticsDataSource[];
  export let selectionKey: keyof BookStatistic;
  export let gridRow: number | undefined;
  export let hasRowInEdit: boolean;
  export let isHidden = false;
  export let title = '';

  const dispatch = createEventDispatcher<{
    propertyChange: StatisticsDataSourceChange;
  }>();

  const tableHeaderClasses =
    'flex items-center py-2.5 px-0 text-sm w-full bg-transparent border-0 md:border-b-2 border-border appearance-none focus:outline-none focus:ring-0 focus:border-border peer lg:text-base';

  let summaryHeaderPopover: Popover;

  $: optionKeys = new Set<keyof BookStatistic>((options || []).map((option) => option.key));

  $: selectedOption = options.find((option) => option.key === selectionKey)!;
</script>

<div
  class={tableHeaderClasses}
  class:hidden={isHidden}
  style:grid-row={gridRow ? `${gridRow}/${gridRow}` : null}
>
  {#if options.length > 1 && !hasRowInEdit}
    <Popover
      placement={'bottom-start'}
      fallbackPlacements={['top']}
      innerContainerStyles={'width: 100%'}
      containerStyles={'flex: 1;'}
      bind:this={summaryHeaderPopover}
    >
      <div {title}>{selectedOption.label}</div>
      <div slot="content" class="flex flex-col overflow-auto w-46 p-2">
        {#each options as option (option.key)}
          <button
            class="flex flex-1 my-2 hover:opacity-50 hover:bg-accent hover:text-foreground"
            on:click|stopPropagation={() => {
              selectedOption = option;
              dispatch('propertyChange', { property: option.key, statisticsSummaryKey });
              summaryHeaderPopover.toggleOpen();
            }}
          >
            {option.label}
          </button>
        {/each}
      </div>
    </Popover>
  {:else}
    <button
      class="flex flex-1 text-left"
      class:cursor-not-allowed={hasRowInEdit}
      disabled={hasRowInEdit}
      {title}
      on:click={() => {
        dispatch('propertyChange', { property: selectedOption.key, statisticsSummaryKey });
      }}
    >
      {selectedOption.label}
    </button>
  {/if}
  <button
    title="Click to select/sort by this Attribute"
    aria-label={`Sort by ${selectedOption.label}`}
    class="ml-4"
    class:opacity-20={!optionKeys.has($lastStatisticsSummarySortProperty$)}
    class:cursor-not-allowed={hasRowInEdit}
    disabled={hasRowInEdit}
    on:click={() =>
      dispatch('propertyChange', { property: selectedOption.key, statisticsSummaryKey })}
  >
    {#if $lastStatisticsSummarySortDirection$ === SortDirection.ASC}
      <AppIcon icon={faArrowUpShortWide} />
    {:else}
      <AppIcon icon={faArrowDownWideShort} />
    {/if}
  </button>
</div>
