// apps/web/src/lib/components/statistics/statistics-title-filter.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import * as Sheet from '$lib/components/ui/sheet';
  import { Button } from '$lib/components/ui/button';
  import CloseButton from '$lib/components/ui/close-button.svelte';
  import { Input } from '$lib/components/ui/input';
  import {
    preFilteredTitlesForStatistics$,
    type StatisticsTitleFilterItem
  } from './statistics-types';
  import {
    lastStatisticsFilterDateRangeOnly$,
    lastStatisticsFilterShowSelectedTitlesOnly$,
    skipKeyDownListener$
  } from '$lib/data/store';
  import { filterStatisticsTitles, statisticsTitlePage } from './title-filter-model';

  export let statisticsTitleFilters: Map<string, boolean>;
  export let titlesInStatisticsDateRange: Set<string>;

  const dispatch = createEventDispatcher<{
    applyFilter: StatisticsTitleFilterItem[];
    clearPrefilter: void;
    close: void;
  }>();
  let titleFilter = '';
  let page = 1;
  let titlesToFilter: StatisticsTitleFilterItem[] = [];
  // Draft selection is private to this opening. Close/Escape never applies it.
  $: titlesToFilter = [...statisticsTitleFilters].map(([title, isSelected]) => ({
    title,
    isSelected
  }));
  $: filteredTitles = filterStatisticsTitles(
    titlesToFilter,
    titleFilter,
    titlesInStatisticsDateRange,
    $lastStatisticsFilterDateRangeOnly$,
    $lastStatisticsFilterShowSelectedTitlesOnly$
  );
  $: current = statisticsTitlePage(filteredTitles, page);

  onMount(() => {
    $skipKeyDownListener$ = true;
    return () => {
      $skipKeyDownListener$ = false;
    };
  });

  function selectTitle(title: string, isSelected: boolean) {
    titlesToFilter = titlesToFilter.map((item) =>
      item.title === title ? { ...item, isSelected } : item
    );
    page = current.page;
  }

  function selectAll(isSelected: boolean) {
    titlesToFilter = titlesToFilter.map((item) => ({ ...item, isSelected }));
    page = 1;
  }
</script>

<div class="filter-panel">
  <div class="flex items-start justify-between gap-3">
    <Sheet.Title class="min-w-0 text-xl font-semibold">Filter books</Sheet.Title>
    <CloseButton aria-label="Close title filter" onclick={() => dispatch('close')} />
  </div>
  <Input
    type="search"
    placeholder="Filter titles"
    aria-label="Filter book titles"
    value={titleFilter}
    oninput={(event) => {
      titleFilter = event.currentTarget.value;
      page = 1;
    }}
  />
  <div class="flex flex-wrap gap-2" role="group" aria-label="Title visibility">
    <Button
      variant={$lastStatisticsFilterDateRangeOnly$ ? 'secondary' : 'ghost'}
      shape="rounded"
      aria-pressed={$lastStatisticsFilterDateRangeOnly$}
      onclick={() => {
        $lastStatisticsFilterDateRangeOnly$ = !$lastStatisticsFilterDateRangeOnly$;
        page = 1;
      }}>Selected dates only</Button
    >
    <Button
      variant={$lastStatisticsFilterShowSelectedTitlesOnly$ ? 'secondary' : 'ghost'}
      shape="rounded"
      aria-pressed={$lastStatisticsFilterShowSelectedTitlesOnly$}
      onclick={() => {
        $lastStatisticsFilterShowSelectedTitlesOnly$ =
          !$lastStatisticsFilterShowSelectedTitlesOnly$;
        page = 1;
      }}>Selected titles only</Button
    >
  </div>
  <div class="flex flex-wrap items-center gap-2">
    <Button variant="ghost" onclick={() => selectAll(true)}>Select All</Button>
    <Button variant="ghost" onclick={() => selectAll(false)}>Remove All</Button>
    {#if $preFilteredTitlesForStatistics$.size}
      <Button variant="outline" onclick={() => dispatch('clearPrefilter')}>Remove Prefilter</Button>
    {/if}
  </div>
  <p role="status" class="text-sm text-muted-foreground">
    {filteredTitles.length} matching titles · {titlesToFilter.filter((item) => item.isSelected).length} selected
  </p>
  {#if current.rows.length}
    <div class="title-list" role="group" aria-label="Book title selection">
      {#each current.rows as item (item.title)}
        <label class="title-row">
          <input
            type="checkbox"
            aria-label={item.title}
            checked={item.isSelected}
            onchange={(event) => selectTitle(item.title, event.currentTarget.checked)}
          />
          <span class:text-muted-foreground={!titlesInStatisticsDateRange.has(item.title)}
            >{item.title}</span
          >
        </label>
      {/each}
    </div>
  {:else}
    <p class="rounded-xl bg-muted p-5 text-center">No Titles to filter</p>
  {/if}
  {#if current.pages > 1}
    <div class="flex flex-wrap items-center justify-between gap-2" aria-label="Title pages">
      <Button
        variant="ghost"
        disabled={current.page === 1}
        onclick={() => (page = current.page - 1)}>Previous</Button
      >
      <span class="text-sm text-muted-foreground">Page {current.page} / {current.pages}</span>
      <Button
        variant="ghost"
        disabled={current.page === current.pages}
        onclick={() => (page = current.page + 1)}>Next</Button
      >
    </div>
  {/if}
  <div class="flex flex-wrap justify-end gap-2 border-t border-border pt-4">
    <Button variant="ghost" onclick={() => dispatch('close')}>Cancel</Button>
    <Button
      variant="secondary"
      onclick={() => {
        dispatch('applyFilter', titlesToFilter);
        dispatch('close');
      }}>Apply Filter</Button
    >
  </div>
</div>

<style>
  .filter-panel {
    display: grid;
    flex-shrink: 0;
    min-width: 0;
    gap: 16px;
    padding: 20px;
    padding-bottom: max(20px, env(safe-area-inset-bottom));
  }
  .title-list {
    overflow: hidden;
    border: 1px solid var(--border);
    border-radius: 12px;
  }
  .title-row {
    display: flex;
    min-height: 52px;
    align-items: center;
    gap: 12px;
    padding: 12px;
    cursor: pointer;
  }
  .title-row + .title-row {
    border-top: 1px solid var(--border);
  }
  .title-row:hover,
  .title-row:focus-within {
    background: var(--muted);
  }
  .title-row input {
    flex-shrink: 0;
    width: 20px;
    height: 20px;
    accent-color: var(--primary);
  }
  .title-row span {
    min-width: 0;
    overflow-wrap: anywhere;
  }
</style>

// apps/web/src/features/statistics/StatisticsTitleFilter.tsx
/**
 * @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors
 * All rights reserved.
 */

import { UiText as Text } from '../../shared-ui/Typography';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, View, StyleSheet } from 'react-native';
import {
  ActionButton,
  NavLink,
  CheckboxField,
  TextField,
  useUiTheme
} from '../../shared-ui/StatisticsPrimitives';
import { TITLE_FILTER_PAGE_SIZE } from '../../lib/components/statistics/title-filter-model';
import { FocusPage } from '../../shared-ui/FocusPage';
import { TitleSelectionRow } from '../../shared-ui/TitleSelectionRow';
import type { StatisticsViewProps } from './view-model';

/** Only the displayed page is local: the shared controller owns the uncommitted
 * selection and retires it on account/route changes and Cancel. */
export function StatisticsTitleFilter({ state, dispatch }: StatisticsViewProps) {
  const { colors } = useUiTheme();
  const { dateOnly, selectedOnly } = state.filterPreferences;
  const setDateOnly = (dateOnly: boolean) =>
    void dispatch({ type: 'filter-preferences', patch: { dateOnly } });
  const setSelectedOnly = (selectedOnly: boolean) =>
    void dispatch({ type: 'filter-preferences', patch: { selectedOnly } });
  const [page, setPage] = useState(1);
  const selected = useMemo(() => new Set(state.titleDraft), [state.titleDraft]);
  const titles = useMemo(
    () =>
      (state.data?.titles ?? []).filter(
        (item) =>
          (!dateOnly || item.inDateRange) &&
          (!selectedOnly || selected.has(item.title)) &&
          item.title
            .normalize('NFC')
            .toLowerCase()
            .includes(state.titleSearch.trim().normalize('NFC').toLowerCase())
      ),
    [state.data?.titles, selected, state.titleSearch, dateOnly, selectedOnly]
  );
  const pageCount = Math.max(1, Math.ceil(titles.length / TITLE_FILTER_PAGE_SIZE));
  const currentPage = Math.min(page, pageCount);
  useEffect(() => setPage(1), [state.titleSearch, dateOnly, selectedOnly]);
  const bulk = (value: boolean) =>
    void dispatch({ type: 'title-all', selected: value, titles: titles.map((item) => item.title) });
  return (
    <View style={styles.panel} testID="statistics-title-filter">
      <TextField
        type="search"
        accessibilityLabel="Filter book titles"
        placeholder="Filter titles"
        value={state.titleSearch}
        onChangeText={(value) => void dispatch({ type: 'title-search', value })}
        editable={!state.busy}
      />
      <View role="group" accessibilityLabel="Title visibility" style={styles.actions}>
        <ActionButton
          variant={dateOnly ? 'secondary' : 'ghost'}
          shape="rounded"
          selected={dateOnly}
          onPress={() => setDateOnly(!dateOnly)}
        >
          Selected dates only
        </ActionButton>
        <ActionButton
          variant={selectedOnly ? 'secondary' : 'ghost'}
          shape="rounded"
          selected={selectedOnly}
          onPress={() => setSelectedOnly(!selectedOnly)}
        >
          Selected titles only
        </ActionButton>
      </View>
      <View style={styles.actions}>
        <ActionButton
          variant="ghost"
          disabled={!titles.length || state.busy}
          onPress={() => bulk(true)}
        >
          Select matching
        </ActionButton>
        <ActionButton
          variant="ghost"
          disabled={!titles.length || state.busy}
          onPress={() => bulk(false)}
        >
          Remove matching
        </ActionButton>
        {(state.query.prefilteredBookKeys.length > 0 ||
          !!state.query.prefilteredTitles?.length ||
          state.query.selectionToken) && (
          <ActionButton
            variant="outline"
            disabled={state.busy}
            onPress={() => void dispatch({ type: 'clear-prefilter' })}
          >
            {state.query.selectionToken ? 'Clear title filter' : 'Remove Prefilter'}
          </ActionButton>
        )}
      </View>
      {state.query.selectionToken && (
        <View style={styles.actions}>
          <Text style={{ color: colors.mutedForeground, fontSize: 14 }}>
            Statistics is scoped to the books selected in Library.
          </Text>
          <NavLink href="/manage" variant="ghost">
            Return to Library
          </NavLink>
        </View>
      )}
      <Text role="status" style={{ color: colors.mutedForeground, fontSize: 14 }}>
        {titles.length} matching titles · {selected.size} selected
      </Text>
      {titles.length ? (
        <View
          role="group"
          accessibilityLabel="Book title selection"
          style={[styles.list, { borderColor: colors.border }]}
        >
          <FocusPage page={currentPage}>
            <FlatList
              data={titles.slice(
                (currentPage - 1) * TITLE_FILTER_PAGE_SIZE,
                currentPage * TITLE_FILTER_PAGE_SIZE
              )}
              keyExtractor={(item) => item.title}
              scrollEnabled={false}
              renderItem={({ item, index }) => (
                <TitleSelectionRow
                  disabled={state.busy}
                  style={index > 0 && { borderTopWidth: 1, borderTopColor: colors.border }}
                >
                  <CheckboxField
                    label={item.title}
                    value={selected.has(item.title)}
                    disabled={state.busy}
                    onValueChange={() => void dispatch({ type: 'title-toggle', title: item.title })}
                    style={{ flex: 1, opacity: item.inDateRange ? 1 : 0.65 }}
                  />
                </TitleSelectionRow>
              )}
            />
          </FocusPage>
        </View>
      ) : (
        <Text style={[styles.empty, { color: colors.foreground, backgroundColor: colors.muted }]}>
          No Titles to filter
        </Text>
      )}
      {pageCount > 1 && (
        <View accessibilityLabel="Title pages" style={styles.pages}>
          <ActionButton
            variant="ghost"
            disabled={currentPage === 1}
            onPress={() => setPage(currentPage - 1)}
          >
            Previous
          </ActionButton>
          <Text style={{ color: colors.mutedForeground, fontSize: 14 }}>
            Page {currentPage} / {pageCount}
          </Text>
          <ActionButton
            variant="ghost"
            disabled={currentPage === pageCount}
            onPress={() => setPage(currentPage + 1)}
          >
            Next
          </ActionButton>
        </View>
      )}
    </View>
  );
}
export function StatisticsTitleFilterFooter({ state, dispatch }: StatisticsViewProps) {
  const { colors } = useUiTheme();
  return (
    <View
      style={[styles.footer, { borderTopColor: colors.border, backgroundColor: colors.popover }]}
    >
      <ActionButton
        variant="ghost"
        disabled={state.busy}
        onPress={() => void dispatch({ type: 'title-filter', open: false })}
      >
        Cancel
      </ActionButton>
      <ActionButton
        variant="secondary"
        disabled={state.busy}
        onPress={() => void dispatch({ type: 'title-apply' })}
      >
        Apply Filter
      </ActionButton>
    </View>
  );
}

const styles = StyleSheet.create({
  panel: { gap: 16, minWidth: 0 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  list: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' },
  empty: { padding: 20, borderRadius: 12, textAlign: 'center' },
  pages: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8
  },
  footer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
    paddingTop: 0
  }
});
