// apps/web/src/settings-react/background-settings.tsx
/**
 * @license BSD-3-Clause
 * Copyright (c) 2026, ッツ Reader Authors
 * All rights reserved.
 */

import React from 'react';
import { useReaderController } from '../reader-react/controller';
import {
  Dom,
  Button,
  Switch,
  useLatest,
  useReaderBindings,
  type ReaderViewProps
} from './primitives';
import { SettingsContext, useSettingsContext } from './context';
import {
  createBackgroundSettings,
  type BackgroundSettingsProps
} from './background-settings-controller';
import { removeBackground, removeBackgrounds } from '../lib/appearance/backgrounds';

export function BackgroundSettings(
  props: Partial<BackgroundSettingsProps> &
    ReaderViewProps & {
      children?: React.ReactNode;
      onClose?: () => void;
      slot?: string;
    }
) {
  const latest = useLatest(props);
  const context = useSettingsContext();
  const c = useReaderController(
    () =>
      createBackgroundSettings(
        props as BackgroundSettingsProps,
        (name, detail) => {
          latest.current.events?.[name]?.({ detail });
          if (name === 'close') latest.current.onClose?.();
        },
        context
      ),
    props
  );
  useReaderBindings(c, props);
  if (!c) return null;
  return (
    <SettingsContext.Provider value={context}>
      <div className="react-settings-background-settings" style={{ display: 'contents' }}>
        <Dom
          as="fieldset"
          aria-busy={c.busy}
          className={['background-setting'].filter(Boolean).join(' ')}
        >
          <Dom as="legend">{c.label}</Dom>
          <Dom as="div" className={['mode-grid'].filter(Boolean).join(' ')}>
            {(c.modes ?? []).map((mode, _index0) => (
              <React.Fragment key={mode.value}>
                {(() => {
                  const image = c.state[mode.value];
                  return (
                    <>
                      <Dom
                        as="section"
                        aria-labelledby={
                          String(c.target ?? '') + '-' + String(mode.value ?? '') + '-heading'
                        }
                        className={['mode-image rounded-2xl bg-muted/40 p-3']
                          .filter(Boolean)
                          .join(' ')}
                      >
                        <Dom
                          as="h3"
                          id={String(c.target ?? '') + '-' + String(mode.value ?? '') + '-heading'}
                        >
                          {mode.label}
                        </Dom>
                        <Dom
                          as="div"
                          aria-hidden={'true'}
                          className={['background-preview', mode.value === 'dark' && 'dark-preview']
                            .filter(Boolean)
                            .join(' ')}
                          style={{
                            backgroundImage: image.url ? `url("${image.url}")` : undefined,
                            '--image-fade-color': mode.fadeColor,
                            '--background-fade': c.opacity
                          }}
                        >
                          {image.url ? (
                            <>
                              <Dom
                                as="span"
                                className={[c.target === 'reader' && 'reader-preview']
                                  .filter(Boolean)
                                  .join(' ')}
                              >
                                {'本を読む'}
                                <Dom as="br" />
                                <Dom as="small">{'Read comfortably'}</Dom>
                              </Dom>
                            </>
                          ) : (
                            <>
                              {' '}
                              <Dom as="span">{'No image'}</Dom>
                            </>
                          )}
                        </Dom>
                        <Button
                          variant={'outline'}
                          onClick={() =>
                            document.getElementById(`background-${c.target}-${mode.value}`)?.click()
                          }
                          disabled={image.busy}
                          className={['w-full'].filter(Boolean).join(' ')}
                        >
                          {'Choose '}
                          {mode.label.toLowerCase()}
                          {' image'}
                        </Button>
                        <Dom
                          as="input"
                          id={
                            'background-' + String(c.target ?? '') + '-' + String(mode.value ?? '')
                          }
                          type={'file'}
                          aria-label={`Choose ${mode.label.toLowerCase()} ${c.label.toLowerCase()}`}
                          accept={'image/png,image/jpeg,image/webp'}
                          disabled={image.busy}
                          className={['sr-only'].filter(Boolean).join(' ')}
                          events={{
                            change: (event: Event & { currentTarget: HTMLInputElement }) =>
                              c.select(mode.value, event)
                          }}
                        />
                        {image.url || image.error ? (
                          <>
                            <Button
                              variant={'ghost'}
                              disabled={image.busy}
                              onClick={() =>
                                removeBackground(c.target, mode.value).catch(() => undefined)
                              }
                              aria-label={
                                'Remove ' +
                                String(mode.label.toLowerCase() ?? '') +
                                ' ' +
                                String(c.label.toLowerCase() ?? '')
                              }
                            >
                              {'Remove'}
                            </Button>
                          </>
                        ) : null}
                        {image.name ? (
                          <>
                            <Dom as="p" className={['filename'].filter(Boolean).join(' ')}>
                              {image.name}
                            </Dom>
                          </>
                        ) : null}
                        {image.busy ? (
                          <>
                            <Dom as="p" role={'status'}>
                              {'Preparing image…'}
                            </Dom>
                          </>
                        ) : null}
                        {image.error ? (
                          <>
                            <Dom
                              as="p"
                              role={'alert'}
                              className={['error'].filter(Boolean).join(' ')}
                            >
                              {image.error}
                            </Dom>
                          </>
                        ) : null}
                      </Dom>
                    </>
                  );
                })()}
              </React.Fragment>
            ))}
          </Dom>
          {c.hasAnything ? (
            <>
              <Button
                variant={'outline'}
                disabled={c.busy}
                onClick={() => removeBackgrounds(c.target).catch(() => undefined)}
                aria-label={'Remove both ' + String(c.label.toLowerCase() ?? '') + ' images'}
                className={['mt-3'].filter(Boolean).join(' ')}
              >
                {'Remove both'}
              </Button>
            </>
          ) : null}
          <Dom as="div" className={['fade-toggle'].filter(Boolean).join(' ')}>
            <Switch
              id={`fade-enabled-${c.target}`}
              checked={c.$options.fade}
              onCheckedChange={(fade) => c.options.next({ ...c.$options, fade })}
              aria-label={`Fade ${c.label.toLowerCase()}`}
            ></Switch>
            <Dom as="label" htmlFor={`fade-enabled-${c.target}`}>
              {'Fade background'}
            </Dom>
          </Dom>
          <Dom
            as="label"
            htmlFor={'fade-' + String(c.target ?? '')}
            className={['fade-label'].filter(Boolean).join(' ')}
          >
            {'Fade amount '}
            <Dom as="output" htmlFor={'fade-' + String(c.target ?? '')}>
              {c.$options.amount}
              {'%'}
            </Dom>
          </Dom>
          <Dom
            as="input"
            id={'fade-' + String(c.target ?? '')}
            type={'range'}
            min={'0'}
            max={'100'}
            step={'1'}
            value={c.$options.amount}
            disabled={!c.$options.fade}
            events={{
              input: (event: Event & { currentTarget: HTMLInputElement }) =>
                c.options.next({ ...c.$options, amount: event.currentTarget.valueAsNumber })
            }}
          />
          <Dom as="p" className={['fade-note'].filter(Boolean).join(' ')}>
            {'Light fades toward white; dark fades toward black.'}
          </Dom>
        </Dom>
      </div>
    </SettingsContext.Provider>
  );
}

// apps/web/src/lib/appearance/background-settings.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Switch } from '$lib/components/ui/switch';
  import {
    backgrounds,
    chooseBackground,
    removeBackground,
    removeBackgrounds
  } from './backgrounds';
  import {
    libraryBackgroundOptions$,
    readerBackgroundOptions$,
    type BackgroundMode,
    type BackgroundTarget
  } from './state';

  export let target: BackgroundTarget;
  export let label: string;

  const modes: { value: BackgroundMode; label: string; fadeColor: string }[] = [
    { value: 'light', label: 'Light', fadeColor: '255 255 255' },
    { value: 'dark', label: 'Dark', fadeColor: '0 0 0' }
  ];

  $: options = target === 'library' ? libraryBackgroundOptions$ : readerBackgroundOptions$;
  $: state = $backgrounds[target];
  $: busy = state.light.busy || state.dark.busy;
  $: hasAnything =
    !!state.light.url || !!state.dark.url || !!state.light.error || !!state.dark.error;
  $: opacity = $options.fade ? $options.amount / 100 : 0;

  async function select(mode: BackgroundMode, event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    input.value = '';
    if (file) await chooseBackground(target, mode, file).catch(() => undefined);
  }
</script>

<fieldset class="background-setting" aria-busy={busy}>
  <legend>{label}</legend>

  <div class="mode-grid">
    {#each modes as mode (mode.value)}
      {@const image = state[mode.value]}
      <section
        class="mode-image rounded-2xl bg-muted/40 p-3"
        aria-labelledby="{target}-{mode.value}-heading"
      >
        <h3 id="{target}-{mode.value}-heading">{mode.label}</h3>
        <div
          class="background-preview"
          class:dark-preview={mode.value === 'dark'}
          style:background-image={image.url ? `url("${image.url}")` : undefined}
          style:--image-fade-color={mode.fadeColor}
          style:--background-fade={opacity}
          aria-hidden="true"
        >
          {#if image.url}
            <span class:reader-preview={target === 'reader'}
              >本を読む<br /><small>Read comfortably</small></span
            >
          {:else}<span>No image</span>{/if}
        </div>

        <Button
          variant="outline"
          class="w-full"
          onclick={() => document.getElementById(`background-${target}-${mode.value}`)?.click()}
          disabled={image.busy}>Choose {mode.label.toLowerCase()} image</Button
        >
        <input
          id="background-{target}-{mode.value}"
          type="file"
          class="sr-only"
          aria-label={`Choose ${mode.label.toLowerCase()} ${label.toLowerCase()}`}
          accept="image/png,image/jpeg,image/webp"
          disabled={image.busy}
          on:change={(event) => select(mode.value, event)}
        />

        {#if image.url || image.error}
          <Button
            variant="ghost"
            disabled={image.busy}
            onclick={() => removeBackground(target, mode.value).catch(() => undefined)}
            aria-label="Remove {mode.label.toLowerCase()} {label.toLowerCase()}">Remove</Button
          >
        {/if}
        {#if image.name}<p class="filename">{image.name}</p>{/if}
        {#if image.busy}<p role="status">Preparing image…</p>{/if}
        {#if image.error}<p role="alert" class="error">{image.error}</p>{/if}
      </section>
    {/each}
  </div>

  {#if hasAnything}
    <Button
      variant="outline"
      class="mt-3"
      disabled={busy}
      onclick={() => removeBackgrounds(target).catch(() => undefined)}
      aria-label="Remove both {label.toLowerCase()} images">Remove both</Button
    >
  {/if}

  <div class="fade-toggle">
    <Switch
      id={`fade-enabled-${target}`}
      checked={$options.fade}
      onCheckedChange={(fade) => options.next({ ...$options, fade })}
      aria-label={`Fade ${label.toLowerCase()}`}
    />
    <label for={`fade-enabled-${target}`}>Fade background</label>
  </div>
  <label for="fade-{target}" class="fade-label"
    >Fade amount
    <output for="fade-{target}">{$options.amount}%</output></label
  >
  <input
    id="fade-{target}"
    type="range"
    min="0"
    max="100"
    step="1"
    value={$options.amount}
    disabled={!$options.fade}
    on:input={(event) => options.next({ ...$options, amount: event.currentTarget.valueAsNumber })}
  />
  <p class="fade-note">Light fades toward white; dark fades toward black.</p>
</fieldset>

<style>
  fieldset {
    min-width: 0;
    border: 1px solid var(--border);
    border-radius: 0.75rem;
    padding: 1rem;
  }
  legend {
    font-weight: 600;
    padding: 0 0.3rem;
  }
  .mode-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(min(100%, 11rem), 1fr));
    gap: 0.9rem;
  }
  .mode-image {
    min-width: 0;
  }
  h3 {
    font-weight: 600;
    font-size: 0.9rem;
    margin-bottom: 0.35rem;
  }
  .background-preview {
    height: 7rem;
    position: relative;
    overflow: hidden;
    border-radius: 0.4rem;
    background-color: #f7f7f7;
    background-size: cover;
    background-position: center;
    margin-bottom: 0.75rem;
  }
  .background-preview.dark-preview {
    background-color: #111;
  }
  .background-preview span {
    position: absolute;
    inset: 0;
    display: grid;
    place-items: center;
    z-index: 1;
    color: #111;
    text-align: center;
    align-content: center;
  }
  .background-preview.dark-preview span {
    color: #f7f7f7;
  }

  .filename {
    overflow-wrap: anywhere;
    color: var(--muted-foreground);
    font-size: 0.8rem;
    margin-top: 0.4rem;
  }
  .fade-toggle {
    display: flex;
    align-items: center;
    gap: 0.6rem;
    margin: 0.85rem 0 0.75rem;
  }
  .fade-label {
    display: flex;
    justify-content: space-between;
    gap: 0.5rem;
    font-size: 0.875rem;
  }
  input[type='range'] {
    width: 100%;
  }
  .fade-note {
    color: var(--muted-foreground);
    font-size: 0.8rem;
    margin-top: 0.3rem;
  }
  .error {
    color: var(--destructive);
    margin-top: 0.5rem;
  }
</style>
